### PR TITLE
feat(ethexe): add `.ethexe.example.toml`, fix node running in Hoodi testnet

### LINKED ISSUE #4907: `ethexe`: add auto-verification for Etherscan API V2
### Problem to Solve

https://github.com/gear-tech/gear/blob/ce8aae2f097c5e3ce60c60061c673bf8eb95b8bd/ethexe/contracts/script/Deployment.s.sol#L131
```
{"status":"0","message":"NOTOK","result":"You are using a deprecated V1 endpoint, switch to Etherscan API V2 using https://docs.etherscan.io/v2-migration"}                                    ~/work/gear/ethexe/contracts   av/eth-value  
```

### Possible Solution

n/a

### Notes

_No response_

### PR DESCRIPTION
**Pull request by StackOverflowExcept1on**
Resolves #4907

### CODE REVIEW

File: ethexe/service/src/lib.rs [hunk 1]
```diff
@@ -231,6 +231,8 @@ impl Service {
                 era_duration: observer.era_duration_secs(),
                 genesis_block_hash: observer.genesis_block_hash(),
             };
+            // TODO: #4918 create Signer object correctly for test environment
+            let signer = Signer::fs(config.node.key_path.parent().unwrap().join("net"));
```
Comment (StackOverflowExcept1on) [inline ethexe/service/src/lib.rs]: #4918

File: .ethexe.example.toml [hunk 2]
```diff
@@ -0,0 +1,191 @@
+### General various node and execution parameters.
+[node]
+# Base directory for all node-related subdirectories.
+# Default locations:
+# - Linux: `$XDG_DATA_HOME/ethexe` or `$HOME/.local/share/ethexe`
+# - macOS: `$HOME/Library/Application Support/com.Gear.ethexe`
+# - Windows: `%APPDATA%\Gear\ethexe\data`
```
Comment (StackOverflowExcept1on) [inline .ethexe.example.toml:7]: mac/win users plz check

File: ethexe/contracts/foundry.toml [hunk 3]
```diff
@@ -34,13 +34,11 @@ exclude_lints = ["asm-keccak256"]
 [rpc_endpoints]
 mainnet = "${MAINNET_RPC_URL}"
 sepolia = "${SEPOLIA_RPC_URL}"
```
Comment (breathx) [inline ethexe/contracts/foundry.toml]: I think we may also rm Sepolia entry

**Review by breathx — APPROVED** [review]
