### PR TITLE
Alternative `#[metawasm]` macro

### LINKED ISSUE #2119: Improve new meta approach
There are some issues with the new meta that are to be fixed:

- [x] No doc comments are allowed inside the trait under `#[metawasm]` attribute-like macro:

    ```rust
    #[metadata]
    pub trait Metawasm {
        /// Doc-comment
        fn method(state: Self::State) -> ... { ... }
    }
    ```

    `error: Functions should not contain attributes`

- [x] No tuple arguments are allowed in methods inside the trait under `#[metawasm]` attribute-like macro:

    ```rust
    #[metadata]
    pub trait Metawasm {
        fn method(arg: (Type1, Type2)) -> ... { ... }
    }
    ```

    `error: Illegal type specification: should be path-based`

    Workaround: use type alias
    
- [ ] Better would be to generate `.metahash` and `meta.txt` in the `target` directory to not add them to `.gitignore`
- [ ] Better to name `meta.txt` according to the Wasm binary file to have several of them in the workspace's `target` directory (say `my_app.meta.txt`)

### PR DESCRIPTION
**Pull request by fluiderson**
Resolves part of #2119.

- Allows doccomments on the `State` type and metawasm functions.
- Replaces the `trait` container with less confusing (IMO) `mod` for the functions.
- Allows up to 18 arguments (excluding the first argument with `State`) instead of 1.
- Allows all types for arguments. [`Decode`](https://docs.rs/parity-scale-codec/latest/parity_scale_codec/trait.Decode.html) will filter out un(en/de)code types.

### CODE REVIEW

File: examples/binaries/new-meta/state-v1/src/wasm.rs [hunk 1]
```diff
@@ -3,18 +3,14 @@ use gmeta::metawasm;
...
-    type State = Vec<Wallet>;
+mod functions {
+    pub type State = Vec<Wallet>;
 
-    fn all_wallets(state: Self::State) -> Vec<Wallet> {
-        state
-    }
-
-    fn first_wallet(state: Self::State) -> Option<Wallet> {
+    pub fn first_wallet(state: State) -> Option<Wallet> {
```
Comment (shamilsan) [inline examples/binaries/new-meta/state-v1/src/wasm.rs:9]: I'd add doc-comments here to demonstrate they are allowed now.

**Review by shamilsan — APPROVED** [review]
Looks good to me. But change `trait` to `mod` forces to rework all programs again.

**Comment by shamilsan** [comment]
@breathx Please take a look

**Review by breathx — CHANGES_REQUESTED** [review]
Looking for a personal discussion before making any decisions on the PR.
But atm waiting for demonstration of added and mentioned in comment functionality here

File: examples/binaries/new-meta/state-v2/src/wasm.rs [hunk 2]
```diff
@@ -3,14 +3,16 @@ use gmeta::metawasm;
...
 
 #[metawasm]
-pub trait Metawasm {
-    type State = Vec<Wallet>;
+pub mod metafuncs {
+    pub type State = Vec<Wallet>;
 
-    fn wallet_by_id(id: Id, state: Self::State) -> Option<Wallet> {
+    /// Returns a wallet with the given `id`.
+    pub fn wallet_by_id(state: State, id: Id) -> Option<Wallet> {
```
Comment (shamilsan) [inline examples/binaries/new-meta/state-v2/src/wasm.rs:10]: Haven't we agreed to demonstrate functions reusing (call one function from another or something similar), aren't we?

**Review by shamilsan — APPROVED** [review]

File: examples/binaries/new-meta/state-v2/src/wasm.rs (hunk 2 above)
Comment (breathx) [reply examples/binaries/new-meta/state-v2/src/wasm.rs:10]: same agreement on demo of multiple arguments

**Review by shamilsan — APPROVED** [review]

File: examples/binaries/new-meta/state-v2/src/wasm.rs [hunk 3]
```diff
@@ -3,14 +3,16 @@ use gmeta::metawasm;
...
         state.into_iter().find(|w| w.id == id)
     }
 
-    fn wallet_by_person(person: Person, state: Self::State) -> Option<Wallet> {
+    /// Returns a wallet of the given `person`.
+    pub fn wallet_by_person(state: State, person: Person) -> Option<Wallet> {
```
Comment (breathx) [inline examples/binaries/new-meta/state-v2/src/wasm.rs:15]: how about parsing Person argument by field directly in fn args?
and also demonstrate more than 1 user arguments parsed

**Comment by shamilsan** [comment]
@breathx Please take a look.

File: gmeta/codegen/src/lib.rs [hunk 4]
```diff
@@ -1,518 +1,503 @@
...
+///     /// Documentation...
+///     pub fn some_function(_: State) -> SomeReturnType {
+///         unimplemented!()
+///     }
+///
+///     pub fn another_function_but_with_arg(mut _state: State, _arg: SomeArg) -> State {
+///         unimplemented!()
+///     }
+///
+///     /// DOCSdocsDoCsdOcSDoCS...
```
Comment (breathx) [inline gmeta/codegen/src/lib.rs:84]:
```suggestion
```
Seems strange for documentation being posted on crates.io some time soon)

File: gmeta/codegen/src/lib.rs [hunk 5]
```diff
@@ -1,518 +1,503 @@
...
+/// - The first argument's type of metafunctions **must** be `State`.
+///
+/// In addition to the mandatory first argument, functions can have additional
+/// ones.
+///
+/// - The maximum amount of additional arguments is 18 due restrictions of the
+/// SCALE codec.
+/// - All additional arguments **must** implement the [`Decode`] &
+/// [`TypeInfo`] traits.
+/// - A function **mustn't** return `()` or nothing.
```
Comment (breathx) [inline gmeta/codegen/src/lib.rs:119]:
```suggestion
/// - A function **mustn't** return `()`.
```

If nothing specified, it means compiler places `-> ()` in Rust

File: gmeta/codegen/src/lib.rs [hunk 6]
```diff
@@ -1,518 +1,503 @@
...
+/// adds `use super::*;` inside the module because, in most cases, it'll be
+/// useful for importing items from an upper namespace. So every item in the
+/// same namespace where the module is located is accessible inside it.
+///
+/// The rest of the magic happens in the another generated private `extern`
+/// module. It registers all metawasm functions, their arguments & return types,
+/// and generates extern functions with the same names. Later, they can be
+/// called from a metaWASM binary inside a blockchain.
+///
+/// **Important note**: although metafunctions can take more than 1 additional
```
Comment (breathx) [inline gmeta/codegen/src/lib.rs:138]: clarify please that this explanation is about underthehood behaviour, not the syntax below macro

File: gmeta/codegen/src/lib.rs [hunk 7]
```diff
@@ -1,518 +1,503 @@
...
+        "module with #[metawasm] mustn't have attributes",
+    ) {
+        return error;
+    }
+
+    if let Err(error) = is_public(module_span, &module.vis) {
+        return error;
+    }
+
+    if module.ident != "metafuncs" {
```
Comment (breathx) [inline gmeta/codegen/src/lib.rs:165]:
```suggestion
// somewhere above: const MOD_NAME: &str = "metafns";
    if module.ident != MOD_NAME {
```

File: gmeta/codegen/src/lib.rs [hunk 8]
```diff
@@ -1,518 +1,503 @@
...
 
-                Ok(())
-            }
-            _ => Err(compile_error(arg, "Self arguments are restricted")),
+        if let (Some(first), Some(second)) = two_first_items {
+            (first, iter::once(second).chain(items))
+        } else {
+            error!(
+                module_span,
+                "module with #[metawasm] must contain at least 2 items"
```
Comment (breathx) [inline gmeta/codegen/src/lib.rs:185]: specify that its about state type and at least 1 fn

File: gmeta/codegen/src/lib.rs [hunk 9]
```diff
@@ -1,518 +1,503 @@
...
+            );
         }
+    } else {
+        error!(
```
Comment (breathx) [inline gmeta/codegen/src/lib.rs:189]: move above, please. for macro fn bodies I prefer not to use too many logic branching

File: gmeta/codegen/src/lib.rs [hunk 10]
```diff
@@ -1,518 +1,503 @@
...
-                    }
-                } else {
-                    unreachable!("Guaranteed by `validate_typed`");
-                }
 
-                *pat_type.ty.as_mut() = state.clone();
-            } else {
-                unreachable!("Guaranteed by `validate_typed`");
-            }
+    // Checking the `State` type
```
Comment (breathx) [inline gmeta/codegen/src/lib.rs:196]:
```suggestion
```

File: gmeta/codegen/src/lib.rs [hunk 11]
```diff
@@ -1,518 +1,503 @@
...
-                "Function shouldn't contain more than 2 args",
-            ))
+    let type_item = if let Item::Type(type_item) = potential_type_item {
+        type_item
+    } else {
+        error!(
+            potential_type_item,
+            "first item of a module with `#[metawasm]` must be a type alias to a state type (e.g. `type State = StateType;`)"
+        );
+    };
```
Comment (breathx) [inline gmeta/codegen/src/lib.rs:204]:
```suggestion
    let Item::Type(type_item) = potential_type_item else {
        error!(
            potential_type_item,
            "first item of a module with `#[metawasm]` must be a type alias to a state type (e.g. `type State = StateType;`)"
        );
    };
```

File: gmeta/codegen/src/lib.rs [hunk 12]
```diff
@@ -1,518 +1,503 @@
...
+    } else {
+        error!(
+            type_item.ident,
+            "identifier of the state type must be `State`"
+        );
     };
 
-    Ok(fn_item)
-}
+    // Checking functions
```
Comment (breathx) [inline gmeta/codegen/src/lib.rs:232]:
```suggestion
```

File: gmeta/codegen/src/lib.rs [hunk 13]
```diff
@@ -1,518 +1,503 @@
...
-    let state_ident = parse_state_ident(maybe_state_item)?;
+    for potential_function in potential_functions {
+        let function = if let Item::Fn(function) = potential_function {
+            function
+        } else {
+            error!(
+                potential_function,
+                "rest of items in a module with `#[metawasm]` must be functions"
+            );
+        };
```
Comment (breathx) [inline gmeta/codegen/src/lib.rs:243]:
```suggestion
        let Item::Fn(function) = potential_function else {
            error!(
                potential_function,
                "rest of items in a module with `#[metawasm]` must be functions"
            );
        };
```

File: gmeta/codegen/src/lib.rs [hunk 14]
```diff
@@ -1,518 +1,503 @@
...
-    for func in funcs {
-        let name = func.sig.ident.clone();
-        let input = func.sig.inputs.len().eq(&2).then(|| {
-            if let FnArg::Typed(pat_type) = &func.sig.inputs[0] {
-                *pat_type.ty.clone()
+        let signature_span = signature.span();
+        let mut inputs = signature.inputs.into_iter();
+
+        // Retrieving the first argument
+
```
Comment (breathx) [inline gmeta/codegen/src/lib.rs:269]:
```suggestion
```

File: gmeta/codegen/src/lib.rs [hunk 15]
```diff
@@ -1,518 +1,503 @@
...
-            unreachable!("Guaranteed by `validate_typed`");
+            error!(
+                signature.paren_token.span,
+                "mustn't be empty, add `state: State` or `_: State`"
+            );
         };
 
-        map.insert(name, (input, output));
-    }
+        // Checking the first argument's type
```
Comment (breathx) [inline gmeta/codegen/src/lib.rs:288]:
```suggestion
```

File: gmeta/codegen/src/lib.rs [hunk 16]
```diff
@@ -1,518 +1,503 @@
...
         }
-    };
-
-    let mut block = quote! {
-        use gmeta::*;
 
-        let mut funcs: BTreeMap<String, TypesRepr> = Default::default();
-        let mut registry = Registry::new();
-    };
+        // Checking the rest of arguments
```
Comment (breathx) [inline gmeta/codegen/src/lib.rs:318]:
```suggestion
```

File: gmeta/codegen/src/lib.rs [hunk 17]
```diff
@@ -1,518 +1,503 @@
...
+                // The rest of arguments can't be the `self` argument because
+                // the compiler won't allow this.
+                unreachable!("unexpected `self` argument");
+            }
         }
-    };
 
-    res.into()
-}
+        // Checking an output
```
Comment (breathx) [inline gmeta/codegen/src/lib.rs:336]:
```suggestion
```

File: gmeta/codegen/src/lib.rs [hunk 18]
```diff
@@ -1,518 +1,503 @@
...
-            extern_token: syn::token::Extern(span),
-            name: Some(LitStr::new("C", span)),
-        });
-        sig.inputs = Default::default();
-        sig.output = ReturnType::Default;
-        func.sig = sig;
+        let return_type = match signature.output {
+            ReturnType::Default => error!(signature_span, "return type must be specified"),
+            ReturnType::Type(_, return_type) => {
+                if let Type::Tuple(tuple) = return_type.as_ref() {
```
Comment (breathx) [inline gmeta/codegen/src/lib.rs:340]: recheck please, that syn has no other ways to detect `unit` type

File: gmeta/codegen/src/lib.rs [hunk 19]
```diff
@@ -1,518 +1,503 @@
...
+            signature.ident,
+            first.pat,
+            arguments,
+            return_type,
+            function.block,
+        ));
+    }
+
+    // Code generating
+
```
Comment (breathx) [inline gmeta/codegen/src/lib.rs:361]:
```suggestion
```

**Review by breathx — APPROVED** [review]
Please make all messages and `.expect()` arguments starting with uppercase letter

**Comment by breathx** [comment]
Well done 👍🏻

File: examples/binaries/new-meta/state-v1/src/wasm.rs [hunk 20]
```diff
@@ -3,18 +3,23 @@ use gmeta::metawasm;
 use gstd::prelude::*;
 
 #[metawasm]
-pub trait Metawasm {
-    type State = Vec<Wallet>;
+pub mod metafuncs {
+    pub type State = Vec<Wallet>;
```
[the remark this answers is not in the document]
Comment (fluiderson) [reply examples/binaries/new-meta/state-v1/src/wasm.rs:7]: Yes.

File: examples/binaries/new-meta/state-v2/src/wasm.rs [hunk 21]
```diff
@@ -3,14 +3,27 @@ use gmeta::metawasm;
...
         state.into_iter().find(|w| w.person == person)
     }
+
+    /// Returns a wallet of a person with the given `name` & `surname`.
+    pub fn wallet_by_name_and_surname(
+        state: State,
+        name: String,
+        surname: String,
+    ) -> Option<Wallet> {
+        wallet_by_person(state, Person { surname, name })
```
[the remark this answers is not in the document]
Comment (fluiderson) [reply examples/binaries/new-meta/state-v2/src/wasm.rs:27]: Like any other function, by `metafuncs::wallet_by_person()`.

If you mean exactly here, then by `super::metafuncs::wallet_by_person()`.

File: gmeta/codegen/Cargo.toml [hunk 22]
```diff
@@ -7,6 +7,12 @@ edition = "2021"
...
-proc-macro2 = "1.0.39"
+syn = { version = "1", default-features = false, features = ["full", "printing", "parsing", "proc-macro", "extra-traits"] }
+quote = { version = "1", default-features = false }
+proc-macro2 = { version = "1", default-features = false }
+
+[dev-dependencies]
+gmeta = { path = "..", features = ["codegen"] }
+gstd = { path = "../../gstd" }
+parity-scale-codec = "3"
+scale-info = "2"
```
[the remark this answers is not in the document]
Comment (fluiderson) [reply gmeta/codegen/Cargo.toml:18]: They're used in a doctest in the macro doccomment.

File: gmeta/codegen/src/lib.rs [hunk 23]
```diff
@@ -1,518 +1,503 @@
...
+            error!(spanned, $message);
         }
     };
+}
+
+fn is_public(spanned: impl Spanned, visibility: &Visibility) -> Result<(), TokenStream> {
+    match visibility {
+        Visibility::Public(_) => Ok(()),
+        other => Err(match other {
+            Visibility::Inherited => error(spanned, "must be public, add the `pub` keyword"),
```
[the remark this answers is not in the document]
Comment (fluiderson) [reply gmeta/codegen/src/lib.rs:33]: Isn't it obvious that adding the `pub` keyword changes visibility?

File: gmeta/codegen/src/lib.rs (hunk 18 above)
Comment (fluiderson) [reply gmeta/codegen/src/lib.rs:340]: https://github.com/dtolnay/syn/pull/858#pullrequestreview-437074058
No, it doesn't.

File: gmeta/codegen/src/lib.rs (hunk 5 above)
Comment (fluiderson) [reply gmeta/codegen/src/lib.rs:119]: You're right. But I think this can be left for Rust newbies. And furthermore, there's a difference between no return type and the unit type for the macro. That's why it has different error messages for both cases.

File: gmeta/codegen/src/lib.rs (hunk 7 above)
Comment (fluiderson) [reply gmeta/codegen/src/lib.rs:165]: What's motivation?

File: gmeta/codegen/src/lib.rs (hunk 10 above)
Comment (fluiderson) [reply gmeta/codegen/src/lib.rs:196]: I prefer to leave the empty line after comment related to a code section. It distinguishes them from comments on particular statements/items/lines.

File: gmeta/codegen/src/lib.rs (hunk 23 above)
[the remark this answers is not in the document]
Comment (breathx) [reply gmeta/codegen/src/lib.rs:33]: yeah, but the sentence seems strange, when just starts with "must be public"
not the deal at all

File: gmeta/codegen/src/lib.rs (hunk 5 above)
Comment (breathx) [reply gmeta/codegen/src/lib.rs:119]: Ok, let it be

File: gmeta/codegen/src/lib.rs (hunk 7 above)
Comment (breathx) [reply gmeta/codegen/src/lib.rs:165]: not to forget change other entries if renamed in future
here one occurrence in comparison and one in static str as error argument. reusing statics isn't the best way for me, but also not the deal, we can leave as it is

File: gmeta/codegen/src/lib.rs (hunk 10 above)
Comment (breathx) [reply gmeta/codegen/src/lib.rs:196]: ok, leave it as it is

**Comment by fluiderson** [comment]
I think error messages should start with lowercase because that's the common style of Rust compile errors. Not sure about ones in `.expect()`, so I'll change them as you suggested.

File: gmeta/codegen/src/lib.rs [hunk 24]
```diff
@@ -6,6 +6,8 @@ use syn::{
     Type, TypePath, Visibility,
 };
 
+static MODULE_NAME: &str = "metafns";
```
Comment (breathx) [inline gmeta/codegen/src/lib.rs:9]: Why `static` instead of `const`?

**Review by breathx — APPROVED** [review]

File: gmeta/codegen/src/lib.rs (hunk 24 above)
Comment (fluiderson) [reply gmeta/codegen/src/lib.rs:9]: I prefer `static` because it's not copied & pasted like `const` but is saved once in the static memory & used by reference.
