### PR TITLE
Change logic of determining the build profile

### LINKED ISSUE #1266: `wasm-builder` fails if the target specified explicitly
### Problem

Programs are built using standard `cargo` command which accepts `--target` flag. If one sets the flag the compilation fails. Found by @ekovalev 

### Steps

On current master:
1. cd utils/economic-checks
2. cargo fuzz run --sanitizer=none simple_fuzz_target

### Possible Solution

_No response_

### Notes

_No response_

### Relevant Log Output

<details><summary>Click to expand/collapse</summary>
<p>

```
error: profile `x86_64-unknown-linux-gnu` is not defined
  error: cargo command run failed: exit status: 101
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `demo-mul-by-const v0.1.0
```

</p>
</details>

### PR DESCRIPTION
**Pull request by gshep**
Resolves #1266 

- add test reproducing the issue
- determine profile in a slightly different way

@gear-tech/dev

### CODE REVIEW

**Review by shamilsan — DISMISSED** [review]

File: utils/wasm-builder/src/wasm_project.rs [hunk 1]
```diff
@@ -52,6 +52,10 @@ impl WasmProject {
             .components()
             .rev()
             .take_while(|c| c.as_os_str() != "target")
+            .collect::<Vec<_>>()
+            .into_iter()
+            .rev()
+            .take_while(|c| c.as_os_str() != "build")
```
Comment (shamilsan) [inline utils/wasm-builder/src/wasm_project.rs:58]: The overall expression looks too complicated. Maybe it is worth to rework it.

**Review by shamilsan — APPROVED** [review]

File: utils/wasm-builder/src/wasm_project.rs (hunk 1 above)
Comment (gshep) [reply utils/wasm-builder/src/wasm_project.rs:58]: Agree. I will introduce a variable to improve readability a bit.

**Review by ekovalev — APPROVED** [review]
