### PR TITLE
fix(gtest): allow zero balance for `exec::exit()`

### LINKED ISSUE #3847: gtest is broken for exec::exit()
any exit leads to:

```
thread 'main' panicked at /Users/nikolayvolf/.cargo/git/checkouts/gear-bdc2b7d48ef3acbd/529cdef/gtest/src/manager.rs:602:13:
An attempt to mint value (0) less than existential deposit (10000000000000)
```

### PR DESCRIPTION
**Pull request by StackOverflowExcept1on**
Resolves #3847

@gear-tech/dev

### CODE REVIEW

**Review by breathx — APPROVED** [review]

**Comment by breathx** [comment]
It's not actually about keeping something alive, but solves the issue

File: gtest/src/manager.rs [hunk 1]
```diff
@@ -598,8 +598,8 @@ impl ExtManager {
         )
     }
 
-    pub(crate) fn mint_to(&mut self, id: &ProgramId, value: Balance) {
-        if value < crate::EXISTENTIAL_DEPOSIT {
+    pub(crate) fn mint_to(&mut self, id: &ProgramId, value: Balance, keep_alive: bool) {
```
Comment (gshep) [inline gtest/src/manager.rs:601]: Perhaps you don't know yet that I personally don't like primitive types especially booleans =) .

This remark is not sufficient but just to mention. Better introduce the new enumuration, for example `MintMode` with two variants `KeepAlive`, `AllowDeath`. Then calls to the method would look like `self.mint_to(&value_destination, balance, MintMode::AllowDeath/KeepAlive);` instead of not much informative `self.mint_to(&value_destination, balance, false/true);`

**Review by gshep — APPROVED** [review]
LGTM!
