### PR TITLE
Fix `gr_unreserve_gas` and `gr_wake` benches

### LINKED ISSUE #1724: BENCHMARKING: fix gr_unreserve_gas bench
### Problem

Currently each call of gr_unreserve_gas returns error: ExecutionError::InvalidReservationId. So execution time is not for _happy_ case.

### Steps

-

### Possible Solution

_No response_

### Notes

_No response_

### Relevant Log Output

<details><summary>Click to expand/collapse</summary>
<p>

```
<Paste your log here>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by ukint-vs**
Resolves #1724  .

- Put `GasReservationMap` into `ActiveProgram` before running bench
- Fix `MessageId` vec size in wasm memory in `gr_wake`

@gear-tech/dev

### CODE REVIEW

**Review by ark0f — APPROVED** [review]

File: runtime/vara/src/weights/pallet_balances.rs [hunk 1]
```diff
@@ -88,37 +88,37 @@ impl<T: frame_system::Config> pallet_balances::WeightInfo for SubstrateWeight<T>
...
 impl WeightInfo for () {
     fn transfer() -> Weight {
-        Weight::from_ref_time(55_241_000 as u64)
+        Weight::from_ref_time(84_789_000 as u64)
             .saturating_add(RocksDbWeight::get().reads(1 as u64))
             .saturating_add(RocksDbWeight::get().writes(1 as u64))
     }
     fn transfer_keep_alive() -> Weight {
-        Weight::from_ref_time(40_852_000 as u64)
+        Weight::from_ref_time(62_856_000 as u64)
```
Comment (NikVolf) [inline runtime/vara/src/weights/pallet_balances.rs:96]: why all these increased?

Comment (ukint-vs) [reply runtime/vara/src/weights/pallet_balances.rs:96]: Possibly due to substrate update. The last time I did not update the weights.

File: pallets/gear/src/benchmarking/syscalls.rs [hunk 2]
```diff
@@ -243,8 +244,18 @@ where
     T: Config,
     T::AccountId: Origin,
 {
-    fn prepare_handle(code: WasmModule<T>, value: u32) -> Result<Exec<T>, &'static str> {
+    fn prepare_handle<PreProcessFn>(
+        code: WasmModule<T>,
+        value: u32,
+        mut pre_process: PreProcessFn,
```
Comment (grishasobol) [inline pallets/gear/src/benchmarking/syscalls.rs:250]: Just recommendation : `prepare_handle` is a function to reduce code size and therefor make code read a little easy. In cases when you need some extra logic , you can use `prepare` function instead.

Comment (grishasobol) [reply pallets/gear/src/benchmarking/syscalls.rs:250]: I think is better to use `prepare` instead of making `pre_process` argument.

**Review by grishasobol — APPROVED** [review]

File: runtime/vara/src/weights/pallet_balances.rs (hunk 1 above)
Comment (grishasobol) [reply runtime/vara/src/weights/pallet_balances.rs:96]: When I made my investigations with benchmarks I'd 2x dispersion for the same benchmark for the same core number, but different time of measurement.

File: pallets/gear/src/benchmarking/syscalls.rs (hunk 2 above)
Comment (ukint-vs) [reply pallets/gear/src/benchmarking/syscalls.rs:250]: I don't see the point of `prepare_handle` fn at all.

Comment (breathx) [reply pallets/gear/src/benchmarking/syscalls.rs:250]: Agree with @grishasobol here

Comment (breathx) [reply pallets/gear/src/benchmarking/syscalls.rs:250]: And even if we come to solution with `pre_process`, the most common way is to throw Option here, instead of each time call empty closure

File: pallets/gear/src/benchmarking/syscalls.rs [hunk 3]
```diff
@@ -805,31 +830,26 @@ where
...
-        }
-        prepare::<T>(
-            instance.caller.into_origin(),
-            HandleKind::Handle(ProgramId::from_origin(instance.addr)),
-            vec![],
-            0u32.into(),
-        )
+        Self::prepare_handle(code, 0, |instance| {
+            for message_id in &message_ids {
+                let message = gear_core::message::Message::new(
```
Comment (breathx) [inline pallets/gear/src/benchmarking/syscalls.rs:835]:
```suggestion
                let message = Message::new(
```

File: pallets/gear/src/benchmarking/syscalls.rs [hunk 4]
```diff
@@ -805,31 +830,26 @@ where
...
+                    Some(1_000_000),
+                    0,
+                    None,
+                );
+                let dispatch = gear_core::message::Dispatch::new(
+                    gear_core::message::DispatchKind::Handle,
+                    message,
+                )
+                .into_stored();
+                WaitlistOf::<T>::insert(dispatch.clone(), u32::MAX.unique_saturated_into())
```
Comment (breathx) [inline pallets/gear/src/benchmarking/syscalls.rs:849]:
```suggestion
                WaitlistOf::<T>::insert(dispatch, u32::MAX.unique_saturated_into())
```

File: pallets/gear/src/benchmarking/syscalls.rs (hunk 3 above)
Comment (breathx) [reply pallets/gear/src/benchmarking/syscalls.rs:835]: You can create `StoredDispatch` at this point

Comment (breathx) [reply pallets/gear/src/benchmarking/syscalls.rs:835]: Everywhere remove this long deps pls

File: pallets/gear/src/benchmarking/syscalls.rs (hunk 4 above)
Comment (breathx) [reply pallets/gear/src/benchmarking/syscalls.rs:849]: I'd also add gas node for a future

File: pallets/gear/src/benchmarking/syscalls.rs [hunk 5]
```diff
@@ -320,43 +331,63 @@ where
...
-            handle_body: Some(body::repeated(
+            handle_body: Some(body::repeated_dyn(
                 r * API_BENCHMARK_BATCH_SIZE,
-                &[
-                    Instruction::I32Const(id_offset as i32),     // id ptr
-                    Instruction::I32Const(amount_offset as i32), // unreserved amount ptr
-                    Instruction::Call(0),
-                    Instruction::Drop,
+                vec![
+                    Counter(
```
Comment (breathx) [inline pallets/gear/src/benchmarking/syscalls.rs:366]: does counter moves on each iteration?

**Review by breathx — CHANGES_REQUESTED** [review]
LGTM at all, but please revert all weights, cause it's totally useless for now

File: pallets/gear/src/benchmarking/syscalls.rs (hunk 5 above)
Comment (ukint-vs) [reply pallets/gear/src/benchmarking/syscalls.rs:366]: yes

File: pallets/gear/src/benchmarking/syscalls.rs [hunk 6]
```diff
@@ -821,14 +846,15 @@ where
                 message,
```
Comment (gshep) [inline pallets/gear/src/benchmarking/syscalls.rs:846]: `gear_core::message::` can be omitted there as well

File: pallets/gear/src/benchmarking/syscalls.rs [hunk 7]
```diff
@@ -326,37 +328,65 @@ where
     // TODO: currently each syscall execution returns error: ExecutionError::InvalidReservationId.
     // We need to fill reservations set with data first. (issue #1724)
```
Comment (gshep) [inline pallets/gear/src/benchmarking/syscalls.rs:329]: Should the comment be removed, shouldn't it?

**Review by gshep — APPROVED** [review]
Looks good!

**Review by breathx — APPROVED** [review]
