### PR TITLE
Handle messages to limbo prog

### LINKED ISSUE #629: Need proper handling for messages with limbro prog destination
Programs are being added to the program storage in extrinsics. That means, that if initialization failed, program still exists in the storage, but with uninitalized state. There is a use case when in the message queue there are init and handle messages to the same destination. If init message fails, the handle message (in the current version) goes to wait list, which is wrong.

Suggestion: the dispatch message should be consumed without any execution, instead of dispatch message should be created a reply message for the original dispatch message source. Discussion around that was made during the dev-team sync call.

### PR DESCRIPTION
**Pull request by SabaunT**
Resolves #629 (#507) and #567

Release Notes: 
1. Value included to the messages is now sent/unreserved only after message was processed. A new journal note was introduced to state balance changes after processing message (this is a pre-req for #644)
2. `Message` storage is now transformed to `Dispatch` (`Message` with entry point).
3. `Program` storage is now transformed to store enum with Active and Terminated programs. Terminated programs are those, which failed to be initialized. Messages to such programs are handled differently.
4. Program limbo was removed due to the previous.

@gear-tech/dev

### CODE REVIEW

File: common/src/lib.rs [hunk 1]
```diff
@@ -215,31 +267,34 @@ pub fn get_code_metadata(code_hash: H256) -> Option<CodeMetadata> {
...
-    /// Program has been successfully initialized and can process messages.
-    Initialized,
-}
-
+// tmp [sab] remove later
 pub fn get_program_state(id: H256) -> Option<ProgramState> {
-    get_program(id).map(|p| p.state)
+    get_program(id)
+        .map(|p| p.try_into().ok())
+        .flatten()
```
Comment (shamilsan) [inline common/src/lib.rs:274]: map + flatten = and_then

Comment (breathx) [reply common/src/lib.rs:274]: Easy arithmetic 😎

**Comment by NikVolf** [comment]
is it stalled @SabaunT ?

File: common/src/lib.rs [hunk 2]
```diff
@@ -52,6 +61,19 @@ pub const GAS_VALUE_PREFIX: &[u8] = b"g::gas_tree";
 
 pub type ExitCode = i32;
 
+#[derive(Clone, Debug, Decode, Encode, PartialEq, TypeInfo)]
+pub struct Dispatch {
+    pub kind: DispatchKind,
+    pub message: Message,
+}
+
+impl Dispatch {
```
Comment (gshep) [inline common/src/lib.rs:70]: If I'm not mistaken this struct is not used there

**Comment by SabaunT** [comment]
> is it stalled

nope, finishing it. Currently fixing raised after CI. Probably today will move from draft.

File: core-processor/src/processor.rs [hunk 3]
```diff
@@ -17,48 +17,50 @@
...
+            Err(e) => process_error(
+                dispatch,
+                initial_nonce,
+                e.gas_amount.burned(),
+                Some(e.reason),
+            ),
+        };
+        return ret;
     }
+    process_skip(dispatch)
```
Comment (gshep) [inline core-processor/src/processor.rs:58]: Shouldn't it be under `else` block?

File: common/src/lib.rs (hunk 2 above)
Comment (SabaunT) [reply common/src/lib.rs:70]: Now we store to the storage not just message, but a message with an entry-point, which is `Dispatch`.

`Dispatch` in `common` is the same as in `core`, except for message type. I will write down release notes

File: common/src/lib.rs [hunk 4]
```diff
@@ -215,31 +318,26 @@ pub fn get_code_metadata(code_hash: H256) -> Option<CodeMetadata> {
...
-    Initialized,
-}
-
-pub fn get_program_state(id: H256) -> Option<ProgramState> {
-    get_program(id).map(|p| p.state)
-}
-
 pub fn set_program_initialized(id: H256) {
-    if let Some(mut p) = get_program(id) {
+    if let Some(Active(mut p)) = get_program(id) {
```
Comment (breathx) [inline common/src/lib.rs:322]: Should we provide panic or return `Err(_)` for not-found cases etc?

File: core-processor/src/common.rs [hunk 5]
```diff
@@ -167,12 +141,12 @@ pub enum JournalNote {
     ///
     /// This should be the last update involving this message id.
     MessageConsumed(MessageId),
-    /// Message was generated.
-    SendMessage {
+    /// Dispatch was generated.
```
Comment (breathx) [inline core-processor/src/common.rs:144]: I would revert this formulation, because actors literally send "messages". It's conversion into dispatch appears under the hood only

File: core/src/message.rs [hunk 6]
```diff
@@ -752,6 +753,65 @@ impl<IG: MessageIdGenerator + 'static> MessageContext<IG> {
...
+    /// Create handle dispatch
+    pub fn handle(message: Message) -> Self {
+        Dispatch {
+            message,
+            kind: DispatchKind::Handle,
+        }
+    }
+
+    /// Create handle reply dispatch
+    pub fn handle_reply(message: Message) -> Self {
```
Comment (breathx) [inline core/src/message.rs:785]:
```suggestion
    pub fn reply(message: Message) -> Self {
```

File: core-processor/src/processor.rs (hunk 3 above)
Comment (breathx) [reply core-processor/src/processor.rs:58]: Yeah

File: gear-test/src/check.rs [hunk 7]
```diff
@@ -488,6 +520,29 @@ where
...
+                        .iter()
+                        .map(|address| address.to_program_id())
+                        .collect();
+                    // Final state returns only active programs
+                    let actual_prog_ids = final_state
+                        .programs
+                        .clone()
+                        .into_iter()
+                        .map(|(id, _)| id)
+                        .collect();
```
Comment (shamilsan) [inline gear-test/src/check.rs:534]: `ProgramId` is a copy type, so there is no need to clone `programs` I guess.

File: common/src/lib.rs [hunk 8]
```diff
@@ -52,6 +61,19 @@ pub const GAS_VALUE_PREFIX: &[u8] = b"g::gas_tree";
 
 pub type ExitCode = i32;
 
+#[derive(Clone, Debug, Decode, Encode, PartialEq, TypeInfo)]
+pub struct Dispatch {
+    pub kind: DispatchKind,
+    pub message: Message,
```
Comment (breathx) [inline common/src/lib.rs:67]: Considering about placing everywhere in Dispatch enum with variants of Native or "Common" messages

File: gear-test/spec/test_failed_program_msg_handling.yaml [hunk 9]
```diff
@@ -0,0 +1,50 @@
...
+          - destination: 100
+            source:
+              kind: id
+              value: 1
+            exitCode: 1
+            payload:
+              kind: utf-8
+              value: "skip"
+            gas_limit: 10000000005
+            value: 0
```
Comment (breathx) [inline gear-test/spec/test_failed_program_msg_handling.yaml:50]: Newline at the end

File: common/src/lib.rs [hunk 10]
```diff
@@ -52,6 +61,19 @@ pub const GAS_VALUE_PREFIX: &[u8] = b"g::gas_tree";
...
+}
+
+impl Dispatch {
+    pub fn handle_reply(message: Message) -> Self {
```
Comment (shamilsan) [inline common/src/lib.rs:71]: I'd rename this function to `new_handle_reply` to reflect its constructor-like nature.

File: common/src/lib.rs [hunk 11]
```diff
@@ -64,14 +86,95 @@ pub struct Message {
 }
 
 #[derive(Clone, Debug, Decode, Encode, PartialEq, TypeInfo)]
-pub struct Program {
+pub enum Program {
+    Active(ActiveProgram),
+    Terminated,
```
Comment (shamilsan) [inline common/src/lib.rs:91]: I don't like this naming. The term `Terminated` may confuse about its purpose.

File: gear-test/src/manager.rs [hunk 12]
```diff
@@ -79,66 +85,70 @@ impl CollectState for InMemoryExtManager {
...
         }
     }
     fn wait_dispatch(&mut self, dispatch: Dispatch) {
         self.message_consumed(dispatch.message.id());
-        self.wait_list.insert(
-            (dispatch.message.dest(), dispatch.message.id()),
-            dispatch.message,
-        );
+        self.wait_list
+            .insert((dispatch.message.dest(), dispatch.message.id()), dispatch);
```
Comment (breathx) [inline gear-test/src/manager.rs:133]: I would provide some functions like `dispatch.id() -> dispatch.message.id()` for comfortable using it

File: common/src/lib.rs [hunk 13]
```diff
@@ -64,14 +86,95 @@ pub struct Message {
...
+}
+
+#[derive(Clone, Copy, Debug)]
+pub enum ProgramError {
+    FailedToGetProgramData,
+    ProgramIsTerminated,
```
Comment (shamilsan) [inline common/src/lib.rs:97]: I'd make them shorter and clearer. Just as an example:
```suggestion
    NoData,
    InitFailed,
```

File: gear-test/src/manager.rs [hunk 14]
```diff
@@ -79,66 +85,70 @@ impl CollectState for InMemoryExtManager {
...
+        if let Some(dispatch) = self.wait_list.remove(&(program_id, awakening_id)) {
+            self.dispatch_queue.push_back(dispatch);
         }
     }
     fn update_nonce(&mut self, program_id: ProgramId, nonce: u64) {
-        if let Some(prog) = self.programs.borrow_mut().get_mut(&program_id) {
+        let mut programs = self.programs.borrow_mut();
+        if let Some(prog) = programs
+            .get_mut(&program_id)
+            .expect("Program not found in storage")
```
Comment (breathx) [inline gear-test/src/manager.rs:149]: this expect panic for each case, except program is Active and it's bad. Terminated program and "Program not found" (user meant) is different cases

File: gear-test/src/sample.rs [hunk 15]
```diff
@@ -88,6 +88,8 @@ pub struct Expectation {
     /// Flag, which points that errors are allowed. Could be used to check traps.
     #[serde(rename = "allowError")]
     pub allow_error: Option<bool>,
+    /// Expected active programs (not failed in the init) ids
+    pub active_programs: Option<Vec<ChainAddress>>,
```
Comment (breathx) [inline gear-test/src/sample.rs:92]: Need to provide "terminated_programs" also to separate progs from users

File: gtest/src/program.rs [hunk 16]
```diff
@@ -172,3 +172,47 @@ impl<'a> Program<'a> {
         self.id
     }
 }
+
```
Comment (breathx) [inline gtest/src/program.rs:175]: Considering now about should be `gtest` unit tests used as core-logic-testing

**Review by shamilsan — COMMENTED** [review]
I don't like that we have similar structures (e.g. `Dispatch`) with similar content yielding in doubling code. Also, I'd cut out the `Message` to `Dispatch` stuff into the separate PR (if it is really needed and unavoidable as it touches a lot of code).

File: pallets/usage/src/lib.rs [hunk 17]
```diff
@@ -343,38 +344,42 @@ pub mod pallet {
...
                                 common::set_program(program_id, program, Default::default());
                             }
                             _ => {
-                                // Must be unreachable: there shouldn't be dangling messages in the WL
-                                // if the associated program has been killed.
-                                // TODO: ensure the above statement always holds:
-                                // https://github.com/gear-tech/gear/issues/507
-                                log::warn!("Failed to find a program with ID: {:?}", program_id);
+                                unreachable!(
+                                    "program with {:?} id was terminated and messages to it were remove from WL",
```
Comment (breathx) [inline pallets/usage/src/lib.rs:369]: Do we remove them atm?

File: pallets/gear/src/manager.rs [hunk 18]
```diff
@@ -405,4 +437,29 @@ where
...
+            );
+            let from = <T::AccountId as Origin>::from_origin(from);
+            let to = <T::AccountId as Origin>::from_origin(to);
+            let _ = T::Currency::repatriate_reserved(
+                &from,
+                &to,
+                value.unique_saturated_into(),
+                BalanceStatus::Free,
+            );
+            return;
```
Comment (breathx) [inline pallets/gear/src/manager.rs:459]: I would place here `else` block also for visibility

**Review by breathx — COMMENTED** [review]
Related to reusing of Dispatch in core and common I really like your idea that we were talking about with encoding and decoding while storage I/O

File: common/src/lib.rs (hunk 11 above)
Comment (SabaunT) [reply common/src/lib.rs:91]: Discussed, leave `Terminated`

File: common/src/lib.rs (hunk 4 above)
Comment (SabaunT) [reply common/src/lib.rs:322]: Yes, will introduce panic. To consider: we discussed using strong types in pallet (and common crate as well), which will prevent such cases (inappropriate use), check storage transition principles.

File: common/src/lib.rs (hunk 8 above)
Comment (SabaunT) [reply common/src/lib.rs:67]: Discussed, next PR

File: core-processor/src/processor.rs (hunk 3 above)
Comment (SabaunT) [reply core-processor/src/processor.rs:58]: you didn't consider return in the `if let`. I will define `else`, so it will be readable.

File: common/src/lib.rs (hunk 10 above)
[the remark this answers is not in the document]
Comment (SabaunT) [reply common/src/lib.rs:71]: Use in different places. Creating `core::message::Dispatch` and then converting it into `common::Dispatch` is inconvenient in usage places.

File: core-processor/src/common.rs (hunk 5 above)
Comment (SabaunT) [reply core-processor/src/common.rs:144]: agreed

File: gear-test/src/manager.rs (hunk 12 above)
Comment (SabaunT) [reply gear-test/src/manager.rs:133]: agreed, next PR when defining only one `Dispatch`

File: pallets/usage/src/lib.rs (hunk 17 above)
Comment (SabaunT) [reply pallets/usage/src/lib.rs:369]: yes, when program was terminated, messaged to it are removed from WL in manager

File: pallets/gear/src/manager.rs (hunk 18 above)
Comment (SabaunT) [reply pallets/gear/src/manager.rs:459]: agreed

File: common/src/lib.rs (hunk 4 above)
Comment (SabaunT) [reply common/src/lib.rs:322]: Agreed, assertions (`expect`) should be on the calling side. When remove common (move to pallet) we need to rewrite it with strong types to avoid wrong storage state transitions, for example, setting program initialized for terminated programs.

File: gear-test/src/sample.rs (hunk 15 above)
Comment (SabaunT) [reply gear-test/src/sample.rs:92]: Actual programs we get from `CollectState`, which now return only active ones. Consider doing in the next PR with `common::Program` and `common::Message` with core ones, because will be much easier and require less code to review.

File: gtest/src/program.rs (hunk 16 above)
Comment (SabaunT) [reply gtest/src/program.rs:175]: new issue will be created

File: common/src/lib.rs (hunk 4 above)
Comment (breathx) [reply common/src/lib.rs]: Could you, please, open the issue for this in `Gear Agenda` project and resolve this conversation

File: gear-test/src/sample.rs (hunk 15 above)
Comment (breathx) [reply gear-test/src/sample.rs:92]: Same here. Provide issue and mention here, please

File: common/src/lib.rs (hunk 4 above)
Comment (SabaunT) [reply common/src/lib.rs]: https://github.com/gear-tech/gear/issues/660

**Review by breathx — APPROVED** [review]
Well done 👍 

Provide one more thing for description: this PR also resolves #507.

Need to wait changes from js side from @osipov-mit (snapshot-reading for node debug-mode). After this, we gonna be ready to rerun CI jobs, bump spec and merge into master.

File: gear-test/src/sample.rs (hunk 15 above)
Comment (SabaunT) [reply gear-test/src/sample.rs:92]: #661

**Comment by SabaunT** [comment]
No more many tasks in one PR.

File: tests/common/src/lib.rs [hunk 19]
```diff
@@ -270,16 +271,10 @@ impl<'a> JournalHandler for Journal<'a> {
...
-                ..
-            } => {
-                panic!(
-                    "Init failure (pid: {:?}, mid: {:?}): {:?}",
-                    program_id, message_id, reason
-                );
+            DispatchOutcome::InitFailure { program_id, .. } => {
+                if let Some(prog) = self.context.programs.get_mut(&program_id) {
+                    *prog = None;
+                }
```
Comment (shamilsan) [inline tests/common/src/lib.rs:277]: Maybe to use `Option::take()`?

```suggestion
                self.context.programs.get_mut(&program_id).take();
```

File: tests/common/src/lib.rs [hunk 20]
```diff
@@ -260,7 +261,7 @@ struct Journal<'a> {
 impl<'a> JournalHandler for Journal<'a> {
     fn message_dispatched(&mut self, outcome: DispatchOutcome) {
         match outcome {
-            DispatchOutcome::Success(_) => {}
+            DispatchOutcome::Success(_) | DispatchOutcome::Skip(_) => {}
```
Comment (shamilsan) [inline tests/common/src/lib.rs:264]: Why to not combine all empty branches into one?
```suggestion
            _ => (),
```

File: tests/common/src/lib.rs [hunk 21]
```diff
@@ -270,16 +271,10 @@ impl<'a> JournalHandler for Journal<'a> {
                 );
             }
             DispatchOutcome::InitSuccess { .. } => {}
```
Comment (shamilsan) [inline tests/common/src/lib.rs:273]: Also, it can be combined with the `_ => ()` branch.

File: tests/common/src/lib.rs (hunk 19 above)
Comment (SabaunT) [reply tests/common/src/lib.rs:277]: discussed

**Review by shamilsan — APPROVED** [review]

**Review by NikVolf — APPROVED** [review]
