### PR TITLE
Unique salt generation

### LINKED ISSUE #693: Default salt management for `create_program`
### Problem to Solve

Users can make mistakes in managing salt. For example, for salt user can use in his factory contract some incrementor. But if someone else deploys the same factory, all the create_program calls will fail, because the code hash and salt (provided with an incrementor) values will be used again.

### Possible Solution

We can provide users with some `CodeDeployManager` from `gstd`, which will manage the salt and other stuff using available on-chain unique, unrepeated data.

### Notes

_No response_

### PR DESCRIPTION
**Pull request by montaglue**
Resolves #693.

- added static mut counter
- and wrapped it in function

@reviewer-or-team

### CODE REVIEW

File: gstd/src/common/primitives.rs [hunk 1]
```diff
@@ -151,6 +151,12 @@ impl TryFrom<&[u8]> for ActorId {
 )]
 pub struct MessageId([u8; 32]);
 
+impl MessageId {
+    pub(crate) fn inner(&self) -> &[u8; 32] {
+        &self.0
+    }
+}
```
Comment (breathx) [inline gstd/src/common/primitives.rs:158]: Why aren't you satisfied with `AsRef<[u8]>` implementation for `MessageId`?

File: gstd/src/prog/default_salt.rs [hunk 2]
```diff
@@ -0,0 +1,36 @@
+// This file is part of Gear.
```
Comment (breathx) [inline gstd/src/prog/default_salt.rs:1]: First of all, I don't like the `default_salt` naming. It's pretty similar to `Default` trait for me.

Merge it into mod or provide mod like `salt_generator` or `generator` or even `salty`. Integrate it by default into `create_program` method, like `create_program_with_salt` or provide some beauty builder pattern solution if you don't like large function names.

File: gstd/src/prog/default_salt.rs [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+static mut DEFAULT_SALT_COUNTER: u32 = 0;
+
+pub fn create_default_salt() -> Vec<u8> {
+    unsafe {
+        DEFAULT_SALT_COUNTER += 1;
+    }
+    [
+        crate::msg::id().inner() as &[u8],
+        &block_height().to_be_bytes(),
+        &unsafe { DEFAULT_SALT_COUNTER }.to_be_bytes(),
```
Comment (breathx) [inline gstd/src/prog/default_salt.rs:33]: separate it with variables, please
it's unreadable!

File: gstd/src/prog/default_salt.rs [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+use gcore::exec::block_height;
+
+static mut DEFAULT_SALT_COUNTER: u32 = 0;
+
+pub fn create_default_salt() -> Vec<u8> {
+    unsafe {
+        DEFAULT_SALT_COUNTER += 1;
+    }
+    [
+        crate::msg::id().inner() as &[u8],
```
Comment (breathx) [inline gstd/src/prog/default_salt.rs:31]: also, swap this arguments places to avoid collisions
use, for example
b"unique_key" + msg_id + counter + code_id

Comment (breathx) [reply gstd/src/prog/default_salt.rs:31]: block-height is useless call here, which consumes gas

File: gstd/src/prog/default_salt.rs [hunk 5]
```diff
@@ -0,0 +1,36 @@
...
+
+// You should have received a copy of the GNU General Public License
+// along with this program. If not, see <https://www.gnu.org/licenses/>.
+
+//! Default salt creation module
+
+use codec::alloc::vec::Vec;
+use gcore::exec::block_height;
+
+static mut DEFAULT_SALT_COUNTER: u32 = 0;
```
Comment (breathx) [inline gstd/src/prog/default_salt.rs:24]:
```suggestion
static mut SALT_NONCE: u64 = 0;
```

File: gstd/src/prog/default_salt.rs [hunk 6]
```diff
@@ -0,0 +1,36 @@
...
+
+pub fn create_default_salt() -> Vec<u8> {
+    unsafe {
+        DEFAULT_SALT_COUNTER += 1;
+    }
```
Comment (breathx) [inline gstd/src/prog/default_salt.rs:29]: Are you sure?
isn't `saturating_add` better?

**Review by breathx — CHANGES_REQUESTED** [review]

**Comment by breathx** [comment]
Docs should also be provided!

File: gstd/src/prog/default_salt.rs (hunk 2 above)
Comment (SabaunT) [reply gstd/src/prog/default_salt.rs:1]: @montaglue originally there was an idea to create some manager, which creates new programs and has default salt management under the hood, generates salt privately. I suggest you going this way, because default salt management means that programmer doesn't think about salt at all, not that he should request default salt.

File: gstd/src/prog/default_salt.rs (hunk 4 above)
Comment (SabaunT) [reply gstd/src/prog/default_salt.rs:31]: what about `b"salt".concat(msg_id).concat(counter)`? Seems it will be enough for uniqueness, isn't it?

**Review by SabaunT — CHANGES_REQUESTED** [review]
I have 2 main suggestions:
1. Introduce some kind of `ProgramCreator` (or other suitable name). The idea is described in the comment.
2. Try isolating unsafe code by wrapping it into safe functions and the using these safe functions with other safe code.

File: gstd/src/common/primitives.rs (hunk 1 above)
Comment (montaglue) [reply gstd/src/common/primitives.rs]: I missed it. Done

File: gstd/src/prog/default_salt.rs (hunk 2 above)
Comment (montaglue) [reply gstd/src/prog/default_salt.rs]: I make ProgramGenerator that creates programs, I suppose new version of interface will be comfortable to use.

File: gstd/src/prog/default_salt.rs (hunk 6 above)
Comment (montaglue) [reply gstd/src/prog/default_salt.rs]: done

File: gstd/src/prog/program_creator.rs [hunk 7]
```diff
@@ -0,0 +1,78 @@
...
+        code_hash: CodeHash,
+        payload: T,
+        gas_limit: u64,
+        value: u128,
+    ) -> ActorId {
+        create_program_with_gas(code_hash, self.get_salt(), payload, gas_limit, value)
+    }
+}
+
+impl Default for ProgramGenerator {
```
Comment (shamilsan) [inline gstd/src/prog/program_creator.rs:74]: Why we can't just derive `Default`?

File: gstd/src/prog/program_creator.rs [hunk 8]
```diff
@@ -0,0 +1,78 @@
...
+    creator_nonce: u32,
+    /// number unique for salt in this creator.
+    salt_nonce: u32,
+}
+
+impl ProgramGenerator {
+    pub fn new() -> Self {
+        ProgramGenerator {
+            creator_nonce: get_salt_generator_nonce(),
+            salt_nonce: 0,
```
Comment (shamilsan) [inline gstd/src/prog/program_creator.rs:48]: `salt_nonce` is always zero?

File: gstd/src/prog/program_creator.rs [hunk 9]
```diff
@@ -0,0 +1,78 @@
...
+        }
+    }
+
+    fn get_salt(&mut self) -> Vec<u8> {
+        // Prefix for not crossing with the user salt.
+        let unique_key = b"unique_key: c5755111a6dc6b7498a5";
+        // Provide salt uniqueness across all programs from other messages.
+        let message_id = crate::msg::id();
+        let creator_nonce = &self.creator_nonce.to_be_bytes();
```
Comment (shamilsan) [inline gstd/src/prog/program_creator.rs:57]: Should we call `get_salt_generator_nonce()` here or not?

**Review by shamilsan — COMMENTED** [review]
A good idea is to add an example or test that demonstrates the new feature.

File: gstd/src/prog/default_salt.rs (hunk 5 above)
Comment (montaglue) [reply gstd/src/prog/default_salt.rs]: Done

File: gstd/src/prog/program_creator.rs (hunk 9 above)
Comment (montaglue) [reply gstd/src/prog/program_creator.rs:57]: No, because, we increment `salt_nonce`. It will negate the whole profit of it.

File: gstd/src/prog/mod.rs [hunk 10]
```diff
@@ -18,6 +18,8 @@
 
 //! Program creation module
 
+pub mod program_creator;
```
Comment (SabaunT) [inline gstd/src/prog/mod.rs:21]: I see no tests for that. The main aim of the test is to guarantee, that no repeated program ids will occur.

Comment (SabaunT) [inline gstd/src/prog/mod.rs:21]: I see no tests for that. The main aim of the test is to guarantee, that no repeated program ids will occur.

**Review by SabaunT — CHANGES_REQUESTED** [review]

File: gstd/src/prog/program_creator.rs [hunk 11]
```diff
@@ -0,0 +1,102 @@
...
+///                 generator.create_program_with_gas(submitted_code, [], 1_000_001, value);
+///             }
+///             SendMessage::Handle(receiver, value) => {
+///                 let _ = msg::send(receiver.into(), b"", value);
+///             }
+///         }
+///     }
+/// }
+/// ```
+#[derive(Default)]
```
[the remark this answers is not in the document]
Comment (montaglue) [reply gstd/src/prog/program_creator.rs]: Done

File: gstd/src/prog/program_creator.rs [hunk 12]
```diff
@@ -0,0 +1,102 @@
...
+
+    pub fn create_program_with_gas<T: AsRef<[u8]>>(
+        &mut self,
+        code_hash: CodeHash,
+        payload: T,
+        gas_limit: u64,
+        value: u128,
+    ) -> ActorId {
+        create_program_with_gas(code_hash, self.get_salt(), payload, gas_limit, value)
+    }
```
[the remark this answers is not in the document]
Comment (montaglue) [reply gstd/src/prog/program_creator.rs]: Done

File: gstd/src/prog/mod.rs (hunk 10 above)
Comment (montaglue) [reply gstd/src/prog/mod.rs]: Added unit test

**Review by breathx — CHANGES_REQUESTED** [review]

File: gstd/src/prog/program_generator.rs [hunk 13]
```diff
@@ -0,0 +1,78 @@
...
+        let n = 10;
+        let salts: Vec<Vec<u8>> = (0..n)
+            .map(|_| unsafe { PROGRAM_GENERATOR.get_salt() })
+            .collect();
+
+        for first_salt in salts.iter() {
+            for second_salt in salts.iter() {
+                assert_eq!(first_salt, second_salt);
+            }
+        }
```
[the remark this answers is not in the document]
Comment (montaglue) [reply gstd/src/prog/program_generator.rs:76]: I changed `assert_eq` to `assert_ne` and don't compare salt with itself anymore

File: gstd/src/prog/program_generator.rs [hunk 14]
```diff
@@ -0,0 +1,78 @@
...
+        value: u128,
+    ) -> Result<ActorId> {
+        let salt = unsafe { PROGRAM_GENERATOR.get_salt() };
+
+        if let Some(gas_limit) = gas_limit {
+            create_program_with_gas(code_hash, salt, payload, gas_limit, value)
+        } else {
+            create_program(code_hash, salt, payload, value)
+        }
+    }
```
[the remark this answers is not in the document]
Comment (montaglue) [reply gstd/src/prog/program_generator.rs:56]: done

File: gstd/src/prog/program_generator.rs [hunk 15]
```diff
@@ -0,0 +1,78 @@
...
+}
+
+#[cfg(test)]
+mod tests {
+    use codec::alloc::vec::Vec;
+
+    use crate::prog::program_generator::PROGRAM_GENERATOR;
```
[the remark this answers is not in the document]
Comment (montaglue) [reply gstd/src/prog/program_generator.rs:63]: done

File: gstd/src/prog/program_generator.rs (hunk 13 above)
[the remark this answers is not in the document]
Comment (breathx) [reply gstd/src/prog/program_generator.rs:76]: > I changed `assert_eq` to `assert_ne` and don't compare salt with itself anymore

Just for future, the best approach to check that some vec contains no duplicates is to store its len, convert vec to set and compare initial and final lens

File: gstd/src/prog/generator.rs [hunk 16]
```diff
@@ -0,0 +1,63 @@
...
+
+// You should have received a copy of the GNU General Public License
+// along with this program. If not, see <https://www.gnu.org/licenses/>.
+
+//! Program generation module
+
+use crate::{common::errors::Result, prog, ActorId, CodeHash};
+use codec::alloc::vec::Vec;
+
+/// [`ProgramGenerator`] allows you to create programs without having to set the
```
Comment (shamilsan) [inline gstd/src/prog/generator.rs:24]: Link to itself?
```suggestion
/// `ProgramGenerator` allows you to create programs without having to set the
```

File: examples/program_generator/src/lib.rs [hunk 17]
```diff
@@ -0,0 +1,27 @@
+#![no_std]
+
+use codec::alloc::vec::Vec;
```
Comment (shamilsan) [inline examples/program_generator/src/lib.rs:3]: You can use the original `alloc` instead of a reexport.

```suggestion
extern crate alloc;

use alloc::vec::Vec;
```

File: examples/program_generator/src/lib.rs [hunk 18]
```diff
@@ -0,0 +1,27 @@
...
+use gstd::{prog::ProgramGenerator, CodeHash};
+
+fn salt_uniqueness_test() {
+    let n = 10;
+    let salts: Vec<Vec<u8>> = (0..n).map(|_| ProgramGenerator::get_salt()).collect();
```
Comment (shamilsan) [inline examples/program_generator/src/lib.rs:10]: We may let the compiler infer the type automatically.
```suggestion
    let salts: Vec<_> = (0..n).map(|_| ProgramGenerator::get_salt()).collect();
```

File: gstd/src/prog/generator.rs (hunk 16 above)
Comment (montaglue) [reply gstd/src/prog/generator.rs]: done

File: examples/program_generator/Cargo.toml [hunk 19]
```diff
@@ -0,0 +1,17 @@
...
+
+[lib]
+crate-type = ["cdylib"]
+
+[dependencies]
+galloc = { path = "../../galloc", default-features = false }
+gcore = { path = "../../gcore", default-features = false }
+gstd = { path = "../../gstd", features = ["debug"] }
+codec = { package = "parity-scale-codec", version = "3.1.2", default-features = false, features = ["derive"] }
+hex-literal = "*"
```
Comment (shamilsan) [inline examples/program_generator/Cargo.toml:16]: Not too good practice to hope that a major release will not break backward compatibility.

File: examples/program_generator/src/lib.rs (hunk 18 above)
Comment (montaglue) [reply examples/program_generator/src/lib.rs]: done

File: gstd/src/prog/generator.rs [hunk 20]
```diff
@@ -0,0 +1,63 @@
...
+
+// You should have received a copy of the GNU General Public License
+// along with this program. If not, see <https://www.gnu.org/licenses/>.
+
+//! Program generation module
+
+use crate::{common::errors::Result, prog, ActorId, CodeHash};
+use codec::alloc::vec::Vec;
+
+/// ProgramGenerator allows you to create programs without having to set the
```
Comment (shamilsan) [inline gstd/src/prog/generator.rs:24]: Ticks are ok. E.g.: https://doc.rust-lang.org/src/alloc/string.rs.html#360
```suggestion
/// `ProgramGenerator` allows you to create programs without having to set the
```

File: examples/program_generator/Cargo.toml (hunk 19 above)
Comment (montaglue) [reply examples/program_generator/Cargo.toml]: done

File: gstd/src/prog/generator.rs (hunk 20 above)
Comment (montaglue) [reply gstd/src/prog/generator.rs]: done

File: gstd/src/prog/program_generator.rs [hunk 21]
```diff
@@ -0,0 +1,78 @@
...
+
+// You should have received a copy of the GNU General Public License
+// along with this program. If not, see <https://www.gnu.org/licenses/>.
+
+//! Program generation module
+
+use crate::{common::errors::Result, ActorId, CodeHash};
+use codec::alloc::vec::Vec;
+
+use super::{create_program, create_program_with_gas};
```
[the remark this answers is not in the document]
Comment (montaglue) [reply gstd/src/prog/program_generator.rs]: done

File: gstd/src/prog/program_generator.rs [hunk 22]
```diff
@@ -0,0 +1,78 @@
...
+
+pub struct ProgramGenerator(u64);
```
[the remark this answers is not in the document]
Comment (montaglue) [reply gstd/src/prog/program_generator.rs]: done

File: examples/program_generator/src/lib.rs [hunk 23]
```diff
@@ -0,0 +1,29 @@
...
+
+fn salt_uniqueness_test() {
+    let n = 10;
+    let salts: Vec<_> = (0..n).map(|_| ProgramGenerator::get_salt()).collect();
+
+    for i in 0..n {
+        for j in (i + 1)..n {
+            assert_ne!(salts[i], salts[j]);
+        }
+    }
```
Comment (breathx) [inline examples/program_generator/src/lib.rs:16]: As I said in previous impl, that's still irrational check!
Please, get vecs len, convert to set, get sets len and compare them!

File: gear-test/spec/test_program_generator.yaml [hunk 24]
```diff
@@ -0,0 +1,29 @@
...
+          value: default
+
+    expected:
+      - programs:
+        ids:
+          - kind: id
+            value: 1
+
+          - kind: h256
+            value: 9c1de0d1359e2a4bd3e474a21527afdb6eaeba3106a167705775af0acac11183
```
Comment (breathx) [inline gear-test/spec/test_program_generator.yaml:29]: I'm thinking about steps addition to show, that this program didn't exist before, but it's up to you

**Review by breathx — CHANGES_REQUESTED** [review]
Requesting changes only due to invalid check for uniqueness.
Fix it and ping me to receive approve!

File: examples/program_generator/src/lib.rs (hunk 23 above)
Comment (shamilsan) [reply examples/program_generator/src/lib.rs]: Fixed.

File: examples/program_generator/Cargo.toml [hunk 25]
```diff
@@ -0,0 +1,17 @@
...
+[lib]
+crate-type = ["cdylib"]
+
+[dependencies]
+galloc = { path = "../../galloc", default-features = false }
+gcore = { path = "../../gcore", default-features = false }
+gstd = { path = "../../gstd", features = ["debug"] }
+codec = { package = "parity-scale-codec", version = "3.1.2", default-features = false, features = ["derive"] }
+hex-literal = "0.3.4"
+
```
[the remark this answers is not in the document]
Comment (shamilsan) [reply examples/program_generator/Cargo.toml]: Great advice, fixed.

File: gstd/src/prog/generator.rs [hunk 26]
```diff
@@ -0,0 +1,63 @@
...
+// You should have received a copy of the GNU General Public License
+// along with this program. If not, see <https://www.gnu.org/licenses/>.
+
+//! Program generation module
+
+use crate::{common::errors::Result, prog, ActorId, CodeHash};
+use codec::alloc::vec::Vec;
+
+/// `ProgramGenerator` allows you to create programs without having to set the
+/// salt manually
```
[the remark this answers is not in the document]
Comment (shamilsan) [reply gstd/src/prog/generator.rs]: Done.

**Review by SabaunT — APPROVED** [review]

**Review by breathx — APPROVED** [review]
