### PR TITLE
Fix get gas spent and update cascade test

### LINKED ISSUE #977: Refactor the algo of getting the gas spent in `get_gas_spent`
### File Location(s)

https://github.com/gear-tech/gear/blob/9bd56a0aa17931985c80ec3fa2377518eacc25bb/pallets/gear/src/lib.rs#L576

### Proposal

We can just get the max gas spent via `JournalNote::GasBurned { amount, .. }`

in case of fixing the node key issue in https://github.com/gear-tech/gear/pull/975, we can not get `remaining_gas` via `T::GasHandler::get_limit(message_id)` after the message has been consumed ( in some cases it would be `None` )

### PR DESCRIPTION
**Pull request by breathx**
- Checkouted from #975 so fixes #977 and contains refactored and right calculation in `get_gas_spent`.
- Provided similar to `get_gas_spent` function `get_gas_burned` which adds up only gas which will never returned.
- Cascade test now depend on this functions return values, not on constants.

@gear-tech/dev

### CODE REVIEW

File: examples/binaries/mul-by-const/src/lib.rs [hunk 1]
```diff
@@ -18,7 +18,7 @@
 
 // This contract recursively composes itself with another contract (the other contract
 // being applied to the input data first): `c(f) = (c(f) . f) x`.
-// Every call to the auto_composer contract incremets the internal `ITER` counter.
+// Every call to the auto_composer contract increments the internal `ITER` counter.
```
Comment (ekovalev) [inline examples/binaries/mul-by-const/src/lib.rs:21]: Looks like a description of some other contract (`demo-compose` most likely). Anyway, I will revisit it later and put a proper description

File: pallets/gear/src/lib.rs [hunk 2]
```diff
@@ -562,39 +569,30 @@ pub mod pallet {
                     )
                 };
 
-                core_processor::handle_journal(journal.clone(), &mut ext_manager);
+                // TODO: Check whether we charge gas fee for submitting code after #646
+                for note in journal.into_iter() {
+                    core_processor::handle_journal(vec![note.clone()], &mut ext_manager);
```
Comment (clearloop) [inline pallets/gear/src/lib.rs:574]: why we still need to handle every journal on this? looks like only
- GasBurned
- WakeMessage
- SendDispatch
- WaitDispatch

spend gas

File: examples/binaries/mul-by-const/src/lib.rs (hunk 1 above)
Comment (breathx) [reply examples/binaries/mul-by-const/src/lib.rs:21]: Yeah, seems like this :S
I don't actually know how it appeared, but yeah, better to resolve in separate PR

File: pallets/gear/src/lib.rs (hunk 2 above)
Comment (breathx) [reply pallets/gear/src/lib.rs:574]: We should handle all journal to apply changes and provide messages.

Lets go through the `get_gas_spent` idea:
It's an RPC call to get the amount of gas needed to success execution.
It works like this:
- We set for the initial message maximum of available gas limit: `T::BlockGasLimit::get()`
- We clean current message queue (It has no effect for storage in RPC-call processing due to overlay, but applies changes on storage inside test, be careful with it)
- We insert initial message into the queue
- We run our queue processing till the moment where there is no messages left
- On each iteration we parse ALL created journal (its notes) to apply proper storage changes, emulating real execution
- To don't be chained with concrete notes (avoiding future collisions, cause we may forget about `get_gas_spent`), we go through all of them in custom parsing - after each note processed we query current gas for initial message to find maximal diff from the initial one - this would be the resulting value we should return to user.

`get_gas_burned` - works the same, but we don't calculate minimal amount of gas needed for success execution (that maximal diff) - we just add up all gas burned to get the diff of the user balance after all executions, cause only this gas won't be returned on consume of the user message.

This stuff needs optimisation and code beautifying, but atm this is solution for issues we ran into.

File: pallets/gear/src/lib.rs [hunk 3]
```diff
@@ -562,39 +569,30 @@ pub mod pallet {
                     )
                 };
 
-                core_processor::handle_journal(journal.clone(), &mut ext_manager);
+                // TODO: Check whether we charge gas fee for submitting code after #646
+                for note in journal.into_iter() {
```
Comment (shamilsan) [inline pallets/gear/src/lib.rs:573]: No need to explicitly call `.into_iter()`.
```suggestion
                for note in journal {
```

File: pallets/gear/src/mock.rs [hunk 4]
```diff
@@ -315,3 +322,182 @@ pub fn calc_handle_gas_spent(source: H256, dest: H256, payload: Vec<u8>) -> (u64
...
+                ProgramId::from_origin(source),
+                actor_id,
+                u64::MAX,
+                T::OutgoingLimit::get(),
+                schedule.host_fn_weights.clone().into_core(),
+            )
+        };
+
+        // TODO: Check whether we charge gas fee for submitting code after #646
+        for note in journal.iter() {
```
Comment (shamilsan) [inline pallets/gear/src/mock.rs:481]: I'd prefer to not call `.iter()` explicitly.
```suggestion
        for note in &journal {
```

**Review by shamilsan — APPROVED** [review]
Looks great to me 👍
