### PR TITLE
Charge correctly in exit_code context

### LINKED ISSUE #1199: Syscall benchmarking for reply info
### Problem

Atm syscalls `gr_reply_to` and `gr_exit_code` costs the same (`Costs::ReplyTo`), but that's incorrect, it should be separated.

### PR DESCRIPTION
**Pull request by ukint-vs**
Resolves #1199 .

@gear-tech/dev

### CODE REVIEW

File: core-processor/src/ext.rs [hunk 1]
```diff
@@ -471,6 +473,15 @@ impl EnvExt for Ext {
         Ok(())
     }
 
+    fn exit_code(&mut self) -> Result<Option<ExitCode>, Self::Error> {
+        self.charge_gas_runtime(RuntimeCosts::ExitCode)?;
+        if let Some(details) = self.context.message_context.current().reply() {
+            Ok(Some(details.into_exit_code()))
+        } else {
+            Ok(None)
+        }
```
Comment (gshep) [inline core-processor/src/ext.rs:482]: Can it be rewritten this way? The same is for `reply_to`.
```suggestion
        Ok(self.context.message_context.current().reply().map(|d| d.into_exit_code()))
```

**Review by gshep — APPROVED** [review]
