### PR TITLE
Provide gasful reply syscalls

### LINKED ISSUE #825: Provide an ability to send reply with gas
### Problem to Solve

At the moment, we only support gasless replies. Such kind of regression after #715.

### Possible Solution

Provide extra syscall `gr_reply_wgas` and wrappers for it

### Notes

_No response_

### PR DESCRIPTION
**Pull request by dimasikOne**
Resolves #825

- ```reply_wgas``` syscall add
- ```reply_commit_wgas``` syscall add
- example tests add

@gear-tech/dev

### CODE REVIEW

File: gcore/src/msg.rs [hunk 1]
```diff
@@ -263,6 +328,49 @@ pub fn reply_commit(value: u128) -> Result<MessageId, ReplyError> {
     }
 }
 
+/// Finalize and send a current reply message with gas limit.
+
```
Comment (NikVolf) [inline gcore/src/msg.rs:332]:
```suggestion
///
```

File: examples/reply/src/lib.rs [hunk 2]
```diff
@@ -0,0 +1,14 @@
+#![no_std]
+
+use gstd::{debug, msg};
+
+#[no_mangle]
+pub unsafe extern "C" fn handle() {
```
Comment (NikVolf) [inline examples/reply/src/lib.rs:6]: where this example is tested?

**Comment by ukint-vs** [comment]
I think you can extend existing example and fixture like `ping` to use `reply_wgas` syscall instead of making another example.

File: examples/reply/src/lib.rs (hunk 2 above)
Comment (dimasikOne) [reply examples/reply/src/lib.rs]: added this test to  ```pong``` fixture as @ukint-vs advised

File: core-backend/sandbox/src/funcs.rs [hunk 3]
```diff
@@ -396,8 +396,35 @@ impl<E: Ext + 'static> FuncsHandler<E> {
...
+            })
+    }
+
+    pub fn reply_wgas(ctx: &mut Runtime<E>, args: &[Value]) -> SyscallOutput {
+        let mut args = args.iter();
+
+        let payload_ptr = pop_i32(&mut args)?;
+        let payload_len = pop_i32(&mut args)?;
+        let value_ptr = pop_i32(&mut args)?;
+        let gas_limit_ptr = pop_i32(&mut args)?;
```
Comment (breathx) [inline core-backend/sandbox/src/funcs.rs:408]: I was already asking for common order of arguments: .. -> payload -> gas limit -> value.

```suggestion
        let gas_limit_ptr = pop_i32(&mut args)?;
        let value_ptr = pop_i32(&mut args)?;
```

Comment (breathx) [reply core-backend/sandbox/src/funcs.rs:408]: To follow other api-style

File: core-backend/sandbox/src/funcs.rs [hunk 4]
```diff
@@ -396,8 +396,35 @@ impl<E: Ext + 'static> FuncsHandler<E> {
...
+
+        ctx.ext
+            .with(|ext| {
+                let payload = funcs::get_vec(&ctx.memory, payload_ptr, payload_len)?;
+                let value = funcs::get_u128(&ctx.memory, value_ptr)?;
+                let gas_limit = funcs::get_u128(&ctx.memory, gas_limit_ptr)?;
```
Comment (breathx) [inline core-backend/sandbox/src/funcs.rs:414]:
```suggestion
                let gas_limit = funcs::get_u128(&ctx.memory, gas_limit_ptr)?;
                let value = funcs::get_u128(&ctx.memory, value_ptr)?;
```

Gas limit aren't u128 type.
It could be thrown as it is: https://github.com/gear-tech/gear/blob/2f2fc42c21e21237c4ea6ead7a59a85d2da903d5/core-backend/sandbox/src/funcs.rs#L114

File: core-backend/sandbox/src/funcs.rs [hunk 5]
```diff
@@ -396,8 +396,35 @@ impl<E: Ext + 'static> FuncsHandler<E> {
...
+                ext.reply(ReplyPacket::new_with_gas(
+                    payload,
+                    gas_limit as GasLimit,
```
Comment (breathx) [inline core-backend/sandbox/src/funcs.rs:417]:
```suggestion
                    gas_limit,
```

File: core-backend/sandbox/src/funcs.rs [hunk 6]
```diff
@@ -421,6 +448,33 @@ impl<E: Ext + 'static> FuncsHandler<E> {
             })
     }
 
+    pub fn reply_commit_wgas(ctx: &mut Runtime<E>, args: &[Value]) -> SyscallOutput {
```
Comment (breathx) [inline core-backend/sandbox/src/funcs.rs:451]: Same as in `reply_wgas`

File: core-backend/sandbox/src/funcs.rs [hunk 7]
```diff
@@ -396,8 +396,35 @@ impl<E: Ext + 'static> FuncsHandler<E> {
...
+            .with(|ext| {
+                let payload = funcs::get_vec(&ctx.memory, payload_ptr, payload_len)?;
+                let value = funcs::get_u128(&ctx.memory, value_ptr)?;
+                let gas_limit = funcs::get_u128(&ctx.memory, gas_limit_ptr)?;
+                ext.reply(ReplyPacket::new_with_gas(
+                    payload,
+                    gas_limit as GasLimit,
+                    value,
+                ))
+                .map(|_| ())
```
Comment (breathx) [inline core-backend/sandbox/src/funcs.rs:420]: Could you please also apply changes related to `on_success_code` for all replies type?

File: core-backend/wasmtime/src/funcs.rs [hunk 8]
```diff
@@ -25,6 +25,7 @@ use alloc::{string::String, vec};
 use gear_backend_common::funcs::*;
 use gear_backend_common::{IntoErrorCode, OnSuccessCode};
 use gear_backend_common::{EXIT_TRAP_STR, LEAVE_TRAP_STR, WAIT_TRAP_STR};
+use gear_core::message::GasLimit;
 use gear_core::{
```
Comment (breathx) [inline core-backend/wasmtime/src/funcs.rs:29]: Merge it pls

File: core-backend/wasmtime/src/funcs.rs [hunk 9]
```diff
@@ -260,6 +261,40 @@ impl<E: Ext + 'static> FuncsHandler<E> {
         Func::wrap(store, func)
     }
 
+    pub fn reply_wgas(store: &mut Store<StoreData<E>>, mem: WasmtimeMemory) -> Func {
```
Comment (breathx) [inline core-backend/wasmtime/src/funcs.rs:264]: Same as in sandbox backend about order of args and types converting.

File: examples/ping/src/lib.rs [hunk 10]
```diff
@@ -14,6 +14,16 @@ pub unsafe extern "C" fn handle() {
         msg::reply_bytes("PONG", 0).unwrap();
     }
 
+    if new_msg == "PING_REPLY_WITH_GAS" {
+        msg::reply_with_gas(b"pong reply with gas message", 0, 0).unwrap();
```
Comment (breathx) [inline examples/ping/src/lib.rs:18]: Better to match here

Comment (breathx) [reply examples/ping/src/lib.rs:18]: And what's the reason to reply with 0 gas? Send some amount to check it further

File: gcore/src/msg.rs [hunk 11]
```diff
@@ -42,7 +42,19 @@ mod sys {
             value_ptr: *const u8,
             message_id_ptr: *mut u8,
         ) -> ErrorCode;
+        pub fn gr_reply_wgas(
```
Comment (breathx) [inline gcore/src/msg.rs:45]: order of args

File: gcore/src/msg.rs [hunk 12]
```diff
@@ -221,6 +233,59 @@ pub fn reply(payload: &[u8], value: u128) -> Result<MessageId, ReplyError> {
     }
 }
 
+/// Send a new message with gas limit as a reply to the message currently being
```
Comment (breathx) [inline gcore/src/msg.rs:236]: Seems better just to refer gasless function that this is the same, but with concrete gas amount

File: gcore/src/msg.rs [hunk 13]
```diff
@@ -263,6 +328,49 @@ pub fn reply_commit(value: u128) -> Result<MessageId, ReplyError> {
     }
 }
 
+/// Finalize and send a current reply message with gas limit.
```
Comment (breathx) [inline gcore/src/msg.rs:331]: Same about docs

File: gear-test/spec/test_ping.yaml [hunk 14]
```diff
@@ -15,15 +15,26 @@ fixtures:
...
-      - step: 2
-        messages: []
+      - log:
+        - destination: 1000001
+          payload:
+            kind: utf-8
+            value: PONG
+        - destination: 1000001
+          payload:
+            kind: utf-8
```
Comment (breathx) [inline gear-test/spec/test_ping.yaml:35]: check gas amount of msg here

File: gstd/src/msg/basic.rs [hunk 15]
```diff
@@ -216,6 +216,44 @@ pub fn reply_bytes<T: AsRef<[u8]>>(payload: T, value: u128) -> Result<MessageId>
     gcore::msg::reply(payload.as_ref(), value).into_contract_result()
 }
 
+/// Send a new message with gas limit as a reply to the message currently being
```
Comment (breathx) [inline gstd/src/msg/basic.rs:219]: Same about docs

File: gstd/src/msg/basic.rs [hunk 16]
```diff
@@ -250,6 +288,40 @@ pub fn reply_commit(value: u128) -> Result<MessageId> {
     gcore::msg::reply_commit(value).into_contract_result()
 }
 
+/// Finalize and send a current reply message with gas limit.
```
Comment (breathx) [inline gstd/src/msg/basic.rs:291]: And here

**Review by breathx — CHANGES_REQUESTED** [review]

File: core-backend/sandbox/src/funcs.rs (hunk 4 above)
Comment (dimasikOne) [reply core-backend/sandbox/src/funcs.rs:414]: ok, sounds good, I'll fix that
But I am wondering- why don't use ```value``` "as it is" too? why do we need a ptr for it?
as I understand we use prt for ```payload``` to cut redundant copy semantic becouse ```payload``` could be big and extra copy will hurt, but that's not not true for ```value```. It has +- same size as ptr

Comment (shamilsan) [reply core-backend/sandbox/src/funcs.rs:414]: We are restricted to use the WebAssembly compatible types only. There is no neither 128-bit numeric value, nor vector type (see e.g. https://docs.rs/wasmi/latest/wasmi/enum.ValueType.html).

File: core-backend/sandbox/src/funcs.rs [hunk 17]
```diff
@@ -382,29 +383,54 @@ impl<E: Ext + 'static> FuncsHandler<E> {
...
+            .with(|ext| {
+                let payload = funcs::get_vec(&ctx.memory, payload_ptr, payload_len)?;
+                let value = funcs::get_u128(&ctx.memory, value_ptr)?;
+                ext.reply(ReplyPacket::new_with_gas(payload, gas_limit, value))
+                    .on_success_code(|message_id| wto(ctx, message_id_ptr, message_id.as_ref()))
+            })
+            .map_err(Into::into)
+            .and_then(|res| res.map(Value::I32).map(ReturnValue::Value))
+            .map_err(|_| {
+                ctx.trap = Some("Trapping: unable to send message");
```
Comment (breathx) [inline core-backend/sandbox/src/funcs.rs:424]:
```suggestion
                ctx.trap = Some("Trapping: unable to send reply with gas");
```

File: core-backend/sandbox/src/funcs.rs [hunk 18]
```diff
@@ -382,29 +383,54 @@ impl<E: Ext + 'static> FuncsHandler<E> {
...
                 ext.reply(ReplyPacket::new(payload, value))
-                    .map(|_| ())
-                    .into_error_code()
+                    .on_success_code(|message_id| wto(ctx, message_id_ptr, message_id.as_ref()))
             })
+            .map_err(Into::into)
             .and_then(|res| res.map(Value::I32).map(ReturnValue::Value))
             .map_err(|_| {
-                ctx.trap = Some("Trapping: unable to send reply message");
+                ctx.trap = Some("Trapping: unable to send message");
```
Comment (breathx) [inline core-backend/sandbox/src/funcs.rs:399]: Why does this trap explanation changed?

```suggestion
                ctx.trap = Some("Trapping: unable to send reply message");
```

File: core-backend/sandbox/src/funcs.rs [hunk 19]
```diff
@@ -421,6 +447,32 @@ impl<E: Ext + 'static> FuncsHandler<E> {
...
+                    Default::default(),
+                    gas_limit,
+                    value,
+                ))
+                .on_success_code(|message_id| wto(ctx, message_id_ptr, message_id.as_ref()))
+            })
+            .map_err(Into::into)
+            .and_then(|res| res.map(Value::I32).map(ReturnValue::Value))
+            .map_err(|_| {
+                ctx.trap = Some("Trapping: unable to send message");
```
Comment (breathx) [inline core-backend/sandbox/src/funcs.rs:471]:
```suggestion
                ctx.trap = Some("Trapping: unable to send reply with gas");
```

File: core-backend/wasmtime/src/funcs.rs [hunk 20]
```diff
@@ -284,6 +313,36 @@ impl<E: Ext + 'static> FuncsHandler<E> {
         Func::wrap(store, func)
     }
 
+    pub fn reply_commit_wgas(store: &mut Store<StoreData<E>>, mem: WasmtimeMemory) -> Func {
+        let func = move |mut caller: Caller<'_, StoreData<E>>,
+                         gas_limit: u64,
```
Comment (breathx) [inline core-backend/wasmtime/src/funcs.rs:318]: there is no u64
```suggestion
                         gas_limit: i64,
```

File: core-backend/wasmtime/src/funcs.rs [hunk 21]
```diff
@@ -284,6 +313,36 @@ impl<E: Ext + 'static> FuncsHandler<E> {
...
+                    write_to_caller_memory(
+                        &mut caller,
+                        &mem,
+                        message_id_ptr as isize as _,
+                        message_id.as_ref(),
+                    )
+                })
+            })
+            .map_err(Trap::new)?
+            .map_err(|_| "Trapping: unable to send message")
```
Comment (breathx) [inline core-backend/wasmtime/src/funcs.rs:340]: Recheck all trap explanations for other places please.

```suggestion
            .map_err(|_| "Trapping: unable to send reply message")
```

File: gstd/src/msg/basic.rs [hunk 22]
```diff
@@ -216,6 +216,43 @@ pub fn reply_bytes<T: AsRef<[u8]>>(payload: T, value: u128) -> Result<MessageId>
     gcore::msg::reply(payload.as_ref(), value).into_contract_result()
 }
 
+/// Send a new message as [`reply`] function but with concrete gas limit.
```
Comment (breathx) [inline gstd/src/msg/basic.rs:219]: Didn't you prefer to place here something like "same as `reply(..)`, but with explicit gas limit" ?

**Review by breathx — APPROVED** [review]
👍
