### PR TITLE
Make reply work by parts

### LINKED ISSUE #293: Add tests for async programs
- [x] Test `send_push` interruption and resuming after calling `send_and_wait` (expected to fail at the moment)
- [x] Test whether the sync code in async handler doesn't execute more than once (may fail at the moment)
- [x] Test whether two `reply`s (one before  `send_and_wait` and one after) will cause an error

### LINKED ISSUE #294: Add a `msg::reply_commit` syscall to `gstd`
Currently, we can call `msg::reply_push` after `msg::reply` to add a payload chunk to the reply. But we can get an inconsistent reply if some trap occurs before the final  `msg::reply_push`.

We need to finalize the reply after calling `msg::reply_commit` when sending the reply by parts. Alternatively, we can use `msg::reply` for sending the whole reply once.

We should return a trap when trying to mix `msg::reply` with `msg::reply_push/reply_commit`.

### LINKED ISSUE #319: `gstd::msg::reply` doesn't reduce gas counter
### Problem

`msg::reply` doesn't reduce gas counter when `msg::send` does.

https://github.com/gear-tech/gear/blob/master/core-runner/src/ext.rs#L95

### Steps

See `examples/async`: `ping` program replies with greater `gas_limit` than it has received from `async`.

### Possible Solution

Call `gas_counter.reduce` in `reply`/`reply_commit`.

### PR DESCRIPTION
**Pull request by breathx**
Fixes #294 and fixes #319. Also closes #293.

@gear-tech/dev

### CODE REVIEW

**Comment by NikVolf** [comment]
We should make this work between `gr-wait` / `gr-wake` -s

File: core-backend/src/funcs.rs [hunk 1]
```diff
@@ -98,17 +98,39 @@ pub(crate) fn read<E: Ext>(ext: LaterExt<E>) -> impl Fn(i32, i32, i32) -> Result
...
+            let message_id =
+                ext.reply_commit(ReplyPacket::new(0, vec![].into(), gas_limit as _, value))?;
+            ext.set_mem(message_id_ptr as isize as _, message_id.as_slice());
+            Ok(())
+        })?;
+        result.map_err(|_| "Trapping: unable to send message")
+    }
+}
+
 pub(crate) fn reply_push<E: Ext>(
```
Comment (Anfid) [inline core-backend/src/funcs.rs:134]: Maybe a message handle should be added as a parameter, obtained from `reply_init` function? This would make API consistent with `send_push`

File: core-backend/src/wasmi/env.rs [hunk 2]
```diff
@@ -205,8 +216,11 @@ impl<E: Ext + 'static> ModuleImportResolver for Environment<E> {
             }
             "gr_reply" => func_instance!(Reply, ValueType::I32,
                 ValueType::I32,
-                ValueType::I64,
+                ValueType::I64,ValueType::I32,
```
Comment (Anfid) [inline core-backend/src/wasmi/env.rs:219]: Bad code formatting

Comment (Anfid) [reply core-backend/src/wasmi/env.rs:219]: Note that rustfmt only works with a small set of widely used macros, otherwise it leaves macro contents unchanged.

File: core-backend/src/funcs.rs (hunk 1 above)
Comment (shamilsan) [reply core-backend/src/funcs.rs:134]: No need I guess as the reply is the only one.

File: core/src/message.rs [hunk 3]
```diff
@@ -653,14 +647,42 @@ impl<IG: MessageIdGenerator + 'static> MessageContext<IG> {
...
+            (payload, msg) => {
+                let mut reply = self.id_generator.borrow_mut().produce_reply(packet);
+
+                let packet_payload = reply.payload.0.clone();
+                reply.payload.0.clear();
+                reply
+                    .payload
+                    .0
+                    .extend_from_slice(&payload.as_ref().unwrap_or(&Payload::default()).0);
+                reply.payload.0.extend_from_slice(&packet_payload);
```
[the remark this answers is not in the document]
Comment (breathx) [reply core/src/message.rs]: Done.

**Comment by NikVolf** [comment]
> > We should make this work between `gr-wait` / `gr-wake` -s
> 
> Not only this, but also sending in parts. But I suppose, it requires separated PR.

you can stub it with panic at least for now

File: core/src/message.rs [hunk 4]
```diff
@@ -662,14 +647,39 @@ impl<IG: MessageIdGenerator + 'static> MessageContext<IG> {
...
+            (payload, msg) => {
+                let mut reply = self.id_generator.borrow_mut().produce_reply(packet);
+
+                reply
+                    .payload
+                    .0
+                    .splice(0..0, payload.take().unwrap_or_default().0);
+
+                *msg = Some(reply);
+                *payload = None;
```
Comment (shamilsan) [inline core/src/message.rs:665]: No need after `take()`.
```suggestion
```

File: core/src/message.rs [hunk 5]
```diff
@@ -707,13 +717,10 @@ impl<IG: MessageIdGenerator + 'static> MessageContext<IG> {
...
-                outgoing.payload.0.clear();
                 outgoing
                     .payload
                     .0
-                    .extend_from_slice(&payload.as_ref().unwrap().0);
-                outgoing.payload.0.extend_from_slice(&packet_payload);
+                    .splice(0..0, payload.take().unwrap_or_default().0);
 
                 *msg = Some(outgoing);
                 *payload = None;
```
Comment (shamilsan) [inline core/src/message.rs:726]:
```suggestion
```

File: core/src/message.rs [hunk 6]
```diff
@@ -123,6 +123,8 @@ pub enum Error {
     OutOfBounds,
     /// An attempt to push a payload into reply that was not set
     NoReplyFound,
+    /// An attempt to interrupt execution with `wait(..)` while some messages wasn't complited
```
Comment (shamilsan) [inline core/src/message.rs:126]:
```suggestion
    /// An attempt to interrupt execution with `wait(..)` while some messages weren't completed
```

File: gcore/src/msg.rs [hunk 7]
```diff
@@ -151,6 +152,43 @@ pub fn reply(payload: &[u8], gas_limit: u64, value: u128) -> MessageId {
     }
 }
 
+/// Finalizes current reply message.
```
Comment (shamilsan) [inline gcore/src/msg.rs:155]: We use imperative tense despite it is not too Rust-doc-like.
```suggestion
/// Finalize current reply message.
```

**Review by shamilsan — APPROVED** [review]
Minor typo.

**Review by shamilsan — APPROVED** [review]
Excellent!
But I don't see the checks result after the last changes... :eyes:

**Comment by breathx** [comment]
> Excellent!
> But I don't see the checks result after the last changes... 👀

I suppose, it's Github temporary troubles

**Review by NikVolf — APPROVED** [review]
