### PR TITLE
fix(ethexe-processor): use a dedicated thread pool for chunked execution

### LINKED ISSUE #4764: `ethexe-processor`: use 3rd-party thread pool for chunk processing
### Problem to Solve

 `ethexe-processor`: use 3rd-party thead pool for chunk processing

### Possible Solution

  `ethexe-processor`: use 3rd-party thead pool for chunk processing

### Notes

_No response_

### PR DESCRIPTION
**Pull request by liferooter**
In the previous implementation threads for chunked execution were spawned using `tokio::task::JoinSet::spawn_blocking`, which uses the thread pool of `tokio`. The new implementation uses thread pool of `rayon` crate, which size is optimized for CPU-bound tasks and doesn't interfere with Tokio.

Closes #4764

### CODE REVIEW

File: ethexe/processor/src/lib.rs [hunk 1]
```diff
@@ -143,10 +147,29 @@ impl Processor {
...
+    pub fn try_clone(&self) -> Result<Self> {
+        Ok(Self {
+            config: self.config.clone(),
+            thread_pool: ThreadPoolBuilder::new()
+                .num_threads(self.config.chunk_processing_threads)
+                .build()?,
+            db: self.db.clone(),
+            creator: self.creator.clone(),
+        })
+    }
```
[the remark this answers is not in the document]
Comment (liferooter) [reply ethexe/processor/src/lib.rs]: `Processor` instances should not be cloned frequently. Also wrapping the thread pool into `Arc` will allow to use it in many locations at the same time, which breaks the guarantee that the thread pool has expected number of available threads.

File: ethexe/processor/src/handling/run.rs [hunk 2]
```diff
@@ -569,6 +569,8 @@ mod chunks_splitting {
 
 mod chunk_execution_spawn {
     use super::*;
+    use futures::prelude::*;
```
Comment (ark0f) [inline ethexe/processor/src/handling/run.rs]: Don't use prelude imports

File: ethexe/processor/src/handling/run.rs [hunk 3]
```diff
@@ -614,8 +617,10 @@ mod chunk_execution_spawn {
                     processing_queue_type,
                     gas_allowance_for_chunk,
                 );
-                (chunk_pos, program_id, new_state_hash, jn, gas_spent)
+                tx.send((chunk_pos, program_id, new_state_hash, jn, gas_spent))
+                    .expect("the main thread should not drop the receiver");
             });
+            join_set.spawn(rx.unwrap_or_else(|_| panic!("worker thread has died")));
```
Comment (ark0f) [inline ethexe/processor/src/handling/run.rs]: Don't spawn tokio task - channel awaiting doesn't require multi-threading and tokio scheduling. Use `FuturesUnordered` instead of `JoinSet`. `oneshot::Receiver` implements `Future` trait.

File: ethexe/processor/src/handling/run.rs (hunk 2 above)
Comment (liferooter) [reply ethexe/processor/src/handling/run.rs]: Why

File: ethexe/processor/src/handling/run.rs (hunk 3 above)
Comment (liferooter) [reply ethexe/processor/src/handling/run.rs]: Fixed by https://github.com/gear-tech/gear/pull/5061/commits/cbeafd8df30fbd2691a37cbc8ccee79904c0110e

File: ethexe/processor/src/handling/run.rs (hunk 2 above)
Comment (liferooter) [reply ethexe/processor/src/handling/run.rs]: Fixed by https://github.com/gear-tech/gear/pull/5061/commits/d233edc3282ccb41b8738b825fb68bf77ac97bce

File: ethexe/processor/src/handling/run.rs [hunk 4]
```diff
@@ -585,38 +587,36 @@ mod chunk_execution_spawn {
     /// earlier the closure will nullify it and skip spawning the job for the program queue as it's empty. If the queue
     /// was already nullified, the closure will return `false` and the job will be spawned as usual.
     /// For more info, see impl of the [`OverlaidContext`].
-    pub(super) fn spawn_chunk_execution<R: RunContext>(
+    pub(super) async fn spawn_chunk_execution(
```
Comment (ark0f) [inline ethexe/processor/src/handling/run.rs:589]: Move comment lines about `check_task_no_run` into `arrange_execution_chunks`

**Review by ark0f — APPROVED** [review]

File: ethexe/processor/src/handling/run.rs (hunk 4 above)
Comment (liferooter) [reply ethexe/processor/src/handling/run.rs:589]: Fixed by https://github.com/gear-tech/gear/pull/5061/commits/9dae163c8301bac45bc8aee8a5d7c082ee32497e
