### PR TITLE
Make `HoldBound` errors reachable

### LINKED ISSUE #1242: `calculate_gas_info` doesn't work for `WaitDispatch`
### Problem

```rust
#[test]
fn calculate_gas_info_for_wait_dispatch_works() { 
    let GasInfo {
        min_limit: init_gas_spent,
        ..
    } = Gear::calculate_gas_info(
        USER_1.into_origin(),
        HandleKind::Init(demo_init_wait::WASM_BINARY.to_vec()),                                                                                   
        EMPTY_PAYLOAD.to_vec(),
        0,
        true,
    ).unwrap();
}
```
https://github.com/gear-tech/gear/blob/39f91ce7745fd98c3c7778db47b256ef43fbc055/pallets/gear/src/internal.rs#L369

also, this reaches https://github.com/gear-tech/gear/blob/39f91ce7745fd98c3c7778db47b256ef43fbc055/pallets/gear/src/internal.rs#L317

### Steps

Write the code snippnet above inside tests.

### Possible Solution

Charge `WaitDispatch` here https://github.com/gear-tech/gear/blob/39f91ce7745fd98c3c7778db47b256ef43fbc055/pallets/gear/src/lib.rs#L820

### Notes

_No response_

### Relevant Log Output

<details><summary>Click to expand/collapse</summary>
<p>

```
<Paste your log here>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by breathx**
Resolves #1242.

- Hold bound api was unstabilised for some time.
- Added tests for calculating gas for wait dispatches, will be useful once api become stable.
- Added field `waited` into `GasInfo`, which shows that `min_limit` is not enough, due to insertion to waitlist (appears in cases of just `gr_wait` without gstd async logic or with gstd async logic, which depend on users)

### CODE REVIEW

File: pallets/gear/src/internal.rs [hunk 1]
```diff
@@ -307,7 +307,11 @@ where
 
         // Validating duration.
         if hold.expected_duration().is_zero() {
-            unreachable!("Failed to figure out correct wait hold bound");
+            // TODO: Replace with unreachable call after:
+            // - `HoldBound` safety usage stabilized;
+            // - Issue #1173 solved.
+            log::error!("Failed to figure out correct wait hold bound");
+            return;
```
Comment (SabaunT) [inline pallets/gear/src/internal.rs:314]: do you plan to remove that asap? it's inappropriate to hold this solution for long, because you can loose messages in a such way.

File: pallets/gear/src/tests.rs [hunk 2]
```diff
@@ -3896,6 +3896,24 @@ fn test_reply_to_terminated_program() {
     })
 }
 
+#[test]
```
Comment (SabaunT) [inline pallets/gear/src/tests.rs:3899]: will you introduce the test from audit repo?

File: pallets/gear/src/internal.rs (hunk 1 above)
Comment (SabaunT) [reply pallets/gear/src/internal.rs:314]: discussed

**Review by gshep — APPROVED** [review]

**Review by SabaunT — APPROVED** [review]

File: pallets/gear/src/tests.rs (hunk 2 above)
Comment (breathx) [reply pallets/gear/src/tests.rs:4042]: Done [here](https://github.com/gear-tech/gear/pull/1276/commits/99850daf49da36bb9c95ec63781a3d9560132e95)

**Comment by breathx** [comment]
Waiting for @osipov-mit feedback

**Comment by breathx** [comment]
This PR also requires runtime-upgrade + update of node binary due to changes in RPC api

**Review by osipov-mit — APPROVED** [review]
