### PR TITLE
fix problem with wasmer fault when lazy pages set sigaction

### LINKED ISSUE #1421: Node drop execution with sigfault
### Problem

When we tries to upload specific contracts to node on M1 macos, then we receive node execution drop with message
```
illegal hardware instruction
```

### Steps

1. env
```
main sc_cli::runner: ⛓  Native runtime: gear-node-1680 (gear-node-1.tx1.au1)
main sc_sysinfo: 💻 Operating system: macos
main sc_sysinfo: 💻 CPU architecture: aarch64
```
2. run node
```
./target/release/gear-node --dev  --execution=wasm
```
3. upload smart contract [lol.wasm.zip](https://github.com/gear-tech/gear/files/9485482/lol.wasm.zip)
4. receive an error during `on_idle`
```
illegal hardware instruction
```

### Possible Solution

May be there is some bugs  in `wasmer` for M1 chip - `wasmer` compile WASM code into machine code with some number of  illegal instructions.

### PR DESCRIPTION
**Pull request by grishasobol**
Resolves #1421

### CODE REVIEW

File: lazy-pages/src/sys/unix.rs [hunk 1]
```diff
@@ -67,9 +68,21 @@ extern "C" fn handle_sigsegv(sig: i32, info: *mut siginfo_t, ucontext: *mut c_vo
 
 pub unsafe fn setup_signal_handler() -> io::Result<()> {
     let handler = signal::SigHandler::SigAction(handle_sigsegv);
+
+    // Set additional SA_ONSTACK and SA_NODEFER to avoid problems with wasmer executor.
+    // See comment from shorturl.at/KMO68 :
+    // ```
+    //  SA_ONSTACK allows us to handle signals on an alternate stack,
```
Comment (ark0f) [inline lazy-pages/src/sys/unix.rs:75]: It won't work without [sigaltstack(2)](https://man7.org/linux/man-pages/man2/sigaltstack.2.html). After the change it will also fix #1444

Comment (grishasobol) [reply lazy-pages/src/sys/unix.rs:75]: > It won't work without sigaltstack(2)
Are you sure about that ? As you can see `runtime-spec` and `pallet` test works well. They don't use `wasmer` as executor. Also I just check it for `wasmi` host executor - all goes right as well. I think it works on a common stack without sigaltstack 

> After the change it will also fix #1444
Really ? Cannot understand why))

Comment (ark0f) [reply lazy-pages/src/sys/unix.rs:75]: > test works well

Hm, maybe because:

> Rust installs an alternate stack with sigaltstack, so we rely on that.

> > After the change it will also fix https://github.com/gear-tech/gear/issues/1444
>
> Really ? Cannot understand why))

If we will install a new stack for each thread - signal won't overlap anymore

Comment (grishasobol) [reply lazy-pages/src/sys/unix.rs:75]: Ok, I see now

File: .github/workflows/CI.yaml [hunk 2]
```diff
@@ -248,7 +248,9 @@ jobs:
         run: ./scripts/gear.sh test client-weights
 
       - name: "Test: Upload programs"
-        run: ./scripts/gear.sh test uploads "$(pwd)/target/wat-examples/wrong_load.wasm"
+        run: |
+          ./scripts/gear.sh test uploads "$(pwd)/target/wat-examples/wrong_load.wasm"
+          ./scripts/gear.sh test uploads "$(pwd)/target/wat-examples/inf_recursion.wasm"
```
Comment (breathx) [inline .github/workflows/CI.yaml:253]:
```suggestion
          ./scripts/gear.sh test uploads \
          "$(pwd)/target/wat-examples/wrong_load.wasm" \
          "$(pwd)/target/wat-examples/inf_recursion.wasm"
```

Comment (grishasobol) [reply .github/workflows/CI.yaml:253]: https://github.com/gear-tech/gear/issues/1462

**Review by breathx — APPROVED** [review]

File: lazy-pages/src/sys/unix.rs [hunk 3]
```diff
@@ -120,21 +138,28 @@ where
     };
 
     let old_sigaction = signal::sigaction(signal, &sig_action).map_err(io::Error::from)?;
-    OLD_SIG_HANDLER.with(|sh| *sh.borrow_mut() = old_sigaction.handler());
+    let handler = old_sigaction.handler();
+    let _ = OLD_SIG_HANDLER
+        .set(handler)
```
Comment (ark0f) [inline lazy-pages/src/sys/unix.rs:143]: Won't we face problem old handler is not saved in multithreading mode?

> Returns Ok(()) if the cell was empty and Err(value) if it was full.

**Review by ark0f — APPROVED** [review]

File: lazy-pages/src/sys/unix.rs (hunk 3 above)
Comment (ark0f) [reply lazy-pages/src/sys/unix.rs:143]: Signal handler is always only one for the whole process - so nvm

Comment (grishasobol) [reply lazy-pages/src/sys/unix.rs:143]: All is ok
