### PR TITLE
benchmarking: fix instr, `reply_push`, `create_program`, optimize performance

### LINKED ISSUE #924: fix benchmarks weights for instructions
### Problem

Current weights for instr execution are not looking rational: 
```
  i64const = 4505
  i64load = 12370
  i64store = 9380
  select = 0
  if = 1565
  br = 0
  br_if = 0
  br_table = 0
  br_table_per_entry = 410
  call = 27370
  call_indirect = 30525
  call_indirect_per_param = 0
  local_get = 0
  local_set = 3185
  local_tee = 0
  global_get = 985
  global_set = 1425
  memory_current = 2655
  i64clz = 0
  i64ctz = 0
  i64popcnt = 0
  i64eqz = 0
  i64extendsi32 = 0
  i64extendui32 = 740
  i32wrapi64 = 760
  i64eq = 0
  i64ne = 0
...
```
This may cause that some programs can executes endless.

### Steps

-

### Possible Solution

As I can see in from file pallets/gear/src/schedule.rs :
Gas weight for one instr is
```
Gas = (2 * Wi - r * Wc) / (2 * BATCH_SIZE)
Wc - benchmarked weight for instr_i64const
Wi - benchmarked weight for current instruction
r - some coefficient which is defined for each operation type separately, see pallets/gear/src/schedule.rs 
Wc and Wi you can found in pallets/gear/src/weights.rs
```
Here sub is saturated so if `r * Wc  > 2 * Wi` gas weight will be zero.
So, this lead to zero weighted instruction.
We need to rerun benchmarks or tune `r` coefficient.

You can use branch gsobol-fix-inf-loop, where I have already made test inf_loop in pallets/gear/src/tests.rs.

### Notes

_No response_

### Relevant Log Output

_No response_

### PR DESCRIPTION
**Pull request by ukint-vs**
Resolves #924 #949 #979  .

Optimizations:
- remove usage of codec in `gear-common::page_key()`
- avoid vector `realloc` in `gear-common::page_key()`
- optimize `thread_local!` vars in `lazy-pages`
- reduce iterator usage for `accessed_pages` in `IntoExtInfo`
- reduce usage of `std::thread::LocalKey::with()`

Comment `test-async-multisig` fixtures because of heavy computation in `Sr25519Pair::verify` #1102 

@gear-tech/dev

### CODE REVIEW

**Review by shamilsan — APPROVED** [review]

**Comment by breathx** [comment]
Is it actually finished and can be reviewed?
A bit confusing with failed tests

**Comment by ukint-vs** [comment]
> Is it actually finished and can be reviewed?
> A bit confusing with failed tests

Not yet. Need to update weights and solve the problem with the lack of gas in the `demo-async-sign` and `demo-async-multisig`.

File: common/src/lib.rs [hunk 1]
```diff
@@ -349,15 +349,20 @@ pub fn program_key(id: H256) -> Vec<u8> {
...
+    key.extend(program_id.as_fixed_bytes());
+    key.extend(b"::");
 
     key
 }
 
 fn page_key(id: H256, page: PageNumber) -> Vec<u8> {
-    let mut key = pages_prefix(id);
+    // try to avoid realloc
+    let mut key = Vec::with_capacity(STORAGE_PROGRAM_PAGES_PREFIX.len() + 38);
```
Comment (breathx) [inline common/src/lib.rs:360]:
```suggestion
    let mut key = Vec::with_capacity(STORAGE_PROGRAM_PAGES_PREFIX.len() + 38);
```

better to avoid explicitly specified vars. we can pre-calculate len upper

File: common/src/lib.rs [hunk 2]
```diff
@@ -349,15 +349,20 @@ pub fn program_key(id: H256) -> Vec<u8> {
 pub fn pages_prefix(program_id: H256) -> Vec<u8> {
     let mut key = Vec::new();
```
Comment (breathx) [inline common/src/lib.rs:350]: here with capacity also

File: common/src/lib.rs [hunk 3]
```diff
@@ -401,9 +406,10 @@ pub fn get_program_page_data(
 }
 
 /// Save page data key in storage
-pub fn save_page_lazy_info(id: H256, page_num: PageNumber) {
-    let key = page_key(id, page_num);
-    gear_ri::gear_ri::save_page_lazy_info(page_num.0, &key);
+pub fn save_page_lazy_info(id: H256, page_nums: &BTreeSet<PageNumber>) {
+    let prefix = pages_prefix(id);
+    let pages = page_nums.iter().map(|p| p.0).collect();
```
Comment (breathx) [inline common/src/lib.rs:411]: here goes one more allocation, cause you copy inner nums.
Replace it with into_iter()

File: gear-test/src/sample.rs [hunk 4]
```diff
@@ -48,7 +48,6 @@ fn de_bytes<'de, D: Deserializer<'de>>(deserializer: D) -> Result<Vec<u8>, D::Er
 /// Program being tested and it's initialization data.
 ///
 /// In test nested structure *program* is one the highest fields. The other one is *fixture*.
-#[allow(clippy::derive_partial_eq_without_eq)]
```
Comment (breathx) [inline gear-test/src/sample.rs:51]: why?
is it fixed on the latest clippy?

File: lazy-pages/src/lib.rs [hunk 5]
```diff
@@ -43,6 +43,19 @@ thread_local! {
     static RELEASED_LAZY_PAGES: RefCell<BTreeMap<LazyPage, Option<PageBuf>>> = RefCell::new(BTreeMap::new());
 }
 
+pub fn save_lazy_pages_info(pages: Vec<u32>, prefix: Vec<u8>) {
+    let pages_keys: BTreeMap<LazyPage, Vec<u8>> = pages
+        .iter()
+        .map(|p| {
+            let mut key = Vec::with_capacity(prefix.len() + 4);
```
Comment (breathx) [inline lazy-pages/src/lib.rs:50]: calculate len instead of just `4`

File: lazy-pages/src/lib.rs [hunk 6]
```diff
@@ -43,6 +43,19 @@ thread_local! {
     static RELEASED_LAZY_PAGES: RefCell<BTreeMap<LazyPage, Option<PageBuf>>> = RefCell::new(BTreeMap::new());
 }
 
+pub fn save_lazy_pages_info(pages: Vec<u32>, prefix: Vec<u8>) {
+    let pages_keys: BTreeMap<LazyPage, Vec<u8>> = pages
+        .iter()
```
Comment (breathx) [inline lazy-pages/src/lib.rs:48]: `into_iter()`, than no `*` will be required further

File: pallets/gear/src/ext.rs [hunk 7]
```diff
@@ -265,10 +259,8 @@ impl EnvExt for LazyPagesExt {
                 continue;
             }
             self.fresh_allocations.insert(wasm_page);
-            wasm_page.to_gear_pages_iter().for_each(|page| {
-                log::trace!("add {:?} to lazy pages", page);
-                save_page_lazy_info(id, page);
-            });
+            let gear_pages: BTreeSet<PageNumber> = wasm_page.to_gear_pages_iter().collect();
```
Comment (breathx) [inline pallets/gear/src/ext.rs:262]: I would provide also into_gear_pages_iter

And also I don't see any reason to collect iter to convert it into it afterward

File: pallets/gear/src/tests.rs [hunk 8]
```diff
@@ -876,7 +876,7 @@ fn block_gas_limit_works() {
 
     init_logger();
     new_test_ext().execute_with(|| {
-        let remaining_weight = 791822425 + 6228060 - 1; // calc gas pid1 + pid2 - 1
+        let remaining_weight = 1080476846 + 41640740 - 1; // calc gas pid1 + pid2 - 1
```
Comment (breathx) [inline pallets/gear/src/tests.rs:879]: here better to also calculate it properly

Comment (breathx) [reply pallets/gear/src/tests.rs:879]: our calculate gas works great now

File: runtime-interface/src/lib.rs [hunk 9]
```diff
@@ -191,10 +191,16 @@ pub trait GearRI {
         mprotect_pages_slice(wasm_mem_addr, &lazy_pages, protect)
     }
 
+    // TODO: deprecated, remove before release
```
Comment (breathx) [inline runtime-interface/src/lib.rs:194]: so add deprecated macro here

**Review by breathx — CHANGES_REQUESTED** [review]

File: gear-test/src/sample.rs (hunk 4 above)
Comment (ukint-vs) [reply gear-test/src/sample.rs:51]: yep

File: pallets/gear/src/tests.rs (hunk 8 above)
Comment (ukint-vs) [reply pallets/gear/src/tests.rs:879]: test is ignored now

File: runtime-interface/src/lib.rs (hunk 9 above)
Comment (ukint-vs) [reply runtime-interface/src/lib.rs:194]: macro can't be put in runtime-interface

**Review by breathx — APPROVED** [review]
