### PR TITLE
fix(ethexe-processor): remove rayon

### LINKED ISSUE #5212: ethexe: potential problem with usage of rayon
### Problem

While running ethexe-node-loader testing on multiple validator this panic was observed:
```
thread '<unnamed>' (52) panicked at runtime-interface/sandbox/src/detail.rs:489:23:
RefCell already borrowed
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::cell::panic_already_borrowed::do_panic::runtime
   3: core::cell::panic_already_borrowed
   4: std::thread::local::LocalKey<T>::with
   5: core::ops::function::FnOnce::call_once
   6: gear_sandbox_interface::detail::memory_new
   7: ethexe_processor::host::api::sandbox::memory_new
   8: <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1,A2),R>>::into_func::wasm_to_host_shim
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: wasmtime_runtime::traphandlers::catch_traps::call_closure
  16: wasmtime_setjmp
  17: wasmtime_runtime::traphandlers::<impl wasmtime_runtime::traphandlers::call_thread_state::CallThreadState>::with
  18: wasmtime_runtime::traphandlers::catch_traps
  19: wasmtime::func::invoke_wasm_and_catch_traps
  20: wasmtime::func::typed::TypedFunc<Params,Results>::call
  21: ethexe_processor::host::InstanceWrapper::run
  22: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
  23: rayon::iter::plumbing::Folder::consume_iter
  24: rayon::iter::plumbing::bridge_producer_consumer::helper
  25: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  26: rayon_core::registry::WorkerThread::wait_until_cold
  27: rayon_core::join::join_context::{{closure}}
  28: rayon::iter::plumbing::bridge_producer_consumer::helper
  29: <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::with_producer
  30: rayon::iter::extend::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend
  31: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter
  32: <wasmer_compiler_singlepass::compiler::SinglepassCompiler as wasmer_compiler::compiler::Compiler>::compile_module
  33: wasmer_compiler::artifact_builders::artifact_builder::ArtifactBuild::new
  34: wasmer_compiler::engine::artifact::Artifact::new
  35: wasmer_compiler::engine::inner::Engine::compile
  36: gear_wasmer_cache::compile_and_write_module
  37: gear_wasmer_cache::get
  38: gear_sandbox_host::sandbox::wasmer_backend::instantiate
  39: std::thread::local::LocalKey<T>::with
  40: core::ops::function::FnOnce::call_once
  41: gear_sandbox_interface::detail::instantiate
  42: ethexe_processor::host::api::sandbox::instantiate
  43: <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1,A2,A3,A4),R>>::into_func::wasm_to_host_shim
  44: <unknown>
  45: <unknown>
  46: <unknown>
```

It seems to be related to recent addition of rayon parallel iterator. 

### Steps

1. Build ethexe & ethexe-node-loader from #5208
2. Start the load test: `./ethexe/scripts/start-local-network.sh --enable-node-loader true --node-loader-batch-size 4 --node-loader-workers 4 --num-validators 8`
3. Wait until it panics; sometimes its fast and sometimes it takes hours, but it always occurs.

### Possible Solution

_No response_

### Notes

_No response_

### Relevant Log Output

_No response_

### PR DESCRIPTION
**Pull request by liferooter**
Rayon's thread reusing policy is incompatible with our `LocalKey<RefCell<_>>` hacks.

Resolves #5212.

### CODE REVIEW

File: ethexe/processor/src/handling/thread_pool.rs [hunk 1]
```diff
@@ -0,0 +1,99 @@
...
+            loop {
+                let Ok((task, sender)) = task_rx.recv() else {
+                    // All connected `ThreadPool` instances were dropped
+                    break;
+                };
+
+                let mut handler = handler.clone();
+
+                // Output receiver could be cancelled
+                let _ = sender.send(handler(task));
```
Comment (playX18) [inline ethexe/processor/src/handling/thread_pool.rs]: Maybe use std::panic::catch_unwind instead of catching it on spawn_task side?

File: ethexe/processor/src/handling/run.rs [hunk 2]
```diff
@@ -542,91 +543,94 @@ mod chunk_execution_spawn {
...
             state_hash: H256,
             instrumented_code: InstrumentedCode,
             code_metadata: CodeMetadata,
             executor: InstanceWrapper,
             db: Box<dyn CASDatabase>,
             gas_allowance_for_chunk: u64,
+            promise_out_tx: Option<mpsc::UnboundedSender<Promise>>,
         }
 
+        static THREAD_POOL: LazyLock<ThreadPool<Executable, Result<ChunkItemOutput>>> =
```
Comment (ark0f) [inline ethexe/processor/src/handling/run.rs:591]: I would extract closure into function for clarity

File: ethexe/processor/src/handling/thread_pool.rs (hunk 1 above)
Comment (ark0f) [reply ethexe/processor/src/handling/thread_pool.rs]: And unit test is good

File: ethexe/processor/src/handling/run.rs [hunk 3]
```diff
@@ -542,91 +543,94 @@ mod chunk_execution_spawn {
...
-                    },
-                )
-                .collect()
-        })
-        .await
-        .expect("Failed to join worker thread");
-
-        Ok(output)
+        stream::iter(output_futures)
+            .buffered(DEFAULT_CHUNK_SIZE.get())
```
Comment (ark0f) [inline ethexe/processor/src/handling/run.rs]: Why we need to limit stream?

File: ethexe/processor/src/handling/thread_pool.rs (hunk 1 above)
Comment (liferooter) [reply ethexe/processor/src/handling/thread_pool.rs]: Fixed by https://github.com/gear-tech/gear/pull/5217/commits/a10682b558bd9c9ec2dd89d5829f73319e2a5864

File: ethexe/processor/src/handling/run.rs (hunk 2 above)
Comment (liferooter) [reply ethexe/processor/src/handling/run.rs:591]: Fixed by https://github.com/gear-tech/gear/pull/5217/commits/a10682b558bd9c9ec2dd89d5829f73319e2a5864

File: ethexe/processor/src/handling/run.rs (hunk 3 above)
Comment (liferooter) [reply ethexe/processor/src/handling/run.rs]: Removed by https://github.com/gear-tech/gear/pull/5217/commits/a10682b558bd9c9ec2dd89d5829f73319e2a5864

File: ethexe/processor/src/handling/thread_pool.rs [hunk 4]
```diff
@@ -0,0 +1,131 @@
...
+        async move { rx.await.expect("Worker thread has died") }
+    }
+
+    pub fn spawn_tasks<II: IntoIterator<Item = I>>(
+        &self,
+        input: II,
+    ) -> impl Stream<Item = Option<O>> {
+        let rxs = input.into_iter().map(|input| self.spawn_task(input));
+
+        stream::iter(rxs).then(|f| f)
```
Comment (ark0f) [inline ethexe/processor/src/handling/thread_pool.rs]:
```suggestion
        let rxs = input.into_iter().map(|input| self.spawn_task(input));

        FuturesUnordered::from_iter(rxs)
```

File: ethexe/processor/src/handling/thread_pool.rs [hunk 5]
```diff
@@ -0,0 +1,131 @@
...
+// You should have received a copy of the GNU General Public License
+// along with this program. If not, see <https://www.gnu.org/licenses/>.
+
+//! Small custom thread pool interface, because `rayon` is too smart
+//! and `threadpool` is not smart enough.
+
+use futures::prelude::*;
+use std::{num::NonZero, panic::UnwindSafe};
+
+type Task<I, O> = (I, tokio::sync::oneshot::Sender<Option<O>>);
```
Comment (ark0f) [inline ethexe/processor/src/handling/thread_pool.rs]:
```suggestion
type Task<I, O> = (I, oneshot::Sender<Option<O>>);
```

File: ethexe/processor/src/handling/thread_pool.rs [hunk 6]
```diff
@@ -0,0 +1,131 @@
...
+    /// Spawns a given task.
+    ///
+    /// Returns `Some(result)` if a worker successfully
+    /// processed the task and `None` if the worker panicked.
+    ///
+    /// # Panics
+    ///
+    /// Panics if worker thread dies despite using
+    /// `std::panic::catch_unwind` around the handler.
+    pub fn spawn_task(&self, input: I) -> impl Future<Output = Option<O>> {
```
Comment (ark0f) [inline ethexe/processor/src/handling/thread_pool.rs]:
```suggestion
    pub fn spawn_task(&self, input: I) -> impl Future<Output = thread::Result<O>> {
```

Return result, so panic info is propagated

Comment (ark0f) [inline ethexe/processor/src/handling/thread_pool.rs]:
```suggestion
    pub fn spawn(&self, input: I) -> impl Future<Output = Option<O>> {
```

Task is implied, because you call method of threadpool

File: ethexe/processor/src/handling/thread_pool.rs [hunk 7]
```diff
@@ -0,0 +1,131 @@
...
+        let (tx, rx) = tokio::sync::oneshot::channel();
+
+        self.task_tx
+            .try_send((input, tx))
+            .expect("The channel is unbounded");
+
+        async move { rx.await.expect("Worker thread has died") }
+    }
+
+    pub fn spawn_tasks<II: IntoIterator<Item = I>>(
```
Comment (ark0f) [inline ethexe/processor/src/handling/thread_pool.rs]:
```suggestion
    pub fn spawn_many<II: IntoIterator<Item = I>>(
```

Comment (ark0f) [inline ethexe/processor/src/handling/thread_pool.rs]: Missing docs

File: ethexe/processor/src/handling/thread_pool.rs (hunk 4 above)
Comment (liferooter) [reply ethexe/processor/src/handling/thread_pool.rs]: In our case we need `FuturesOrdered`

Comment (liferooter) [reply ethexe/processor/src/handling/thread_pool.rs]: Fixed in https://github.com/gear-tech/gear/pull/5217/commits/2212ffac1bfd61a31f5a0f67edef57d5283fc7f5

File: ethexe/processor/src/handling/thread_pool.rs (hunk 7 above)
Comment (liferooter) [reply ethexe/processor/src/handling/thread_pool.rs]: Fixed by https://github.com/gear-tech/gear/pull/5217/commits/7b325095f399f6d82ecee51bcef2bb069d082dd5

Comment (liferooter) [reply ethexe/processor/src/handling/thread_pool.rs]: Fixed by https://github.com/gear-tech/gear/pull/5217/commits/7b325095f399f6d82ecee51bcef2bb069d082dd5

File: ethexe/processor/src/handling/thread_pool.rs (hunk 6 above)
Comment (liferooter) [reply ethexe/processor/src/handling/thread_pool.rs]: Fixed by https://github.com/gear-tech/gear/pull/5217/commits/7b325095f399f6d82ecee51bcef2bb069d082dd5

Comment (liferooter) [reply ethexe/processor/src/handling/thread_pool.rs]: Fixed by https://github.com/gear-tech/gear/pull/5217/commits/7b325095f399f6d82ecee51bcef2bb069d082dd5

File: ethexe/processor/src/handling/thread_pool.rs (hunk 5 above)
Comment (liferooter) [reply ethexe/processor/src/handling/thread_pool.rs]: In the context with different channels from both `tokio` and `crossbeam` I consider it good to explicitly show which one (async from `tokio` or blocking from `crossbeam`) it is. That's the reason why I qualify them both with their full names.

File: ethexe/processor/src/handling/thread_pool.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (liferooter) [reply ethexe/processor/src/handling/thread_pool.rs]: It doesn't really matters in this case, since the futures are spawned before any polling.

The behaviour was considered not rustish enough and changed in later commits, so now `FuturesOrdered` are used.

File: ethexe/processor/src/handling/thread_pool.rs [hunk 8]
```diff
@@ -0,0 +1,137 @@
...
+where
+    I: Send + UnwindSafe + 'static,
+    O: Send + 'static,
+{
+    /// Creates a new thread pool.
+    pub fn new<F>(handler: F) -> Self
+    where
+        F: FnMut(I) -> O + Send + Clone + UnwindSafe + 'static,
+    {
+        let n_cpus = std::thread::available_parallelism().map_or(1, NonZero::get);
```
Comment (ark0f) [inline ethexe/processor/src/handling/thread_pool.rs]:
```suggestion
        let n_cpus = thread::available_parallelism().map_or(1, NonZero::get);
```

If you already use `thread::Result` then consistency should be preferred

File: ethexe/processor/src/handling/run.rs [hunk 9]
```diff
@@ -542,91 +543,96 @@ mod chunk_execution_spawn {
...
             state_hash: H256,
             instrumented_code: InstrumentedCode,
             code_metadata: CodeMetadata,
             executor: InstanceWrapper,
             db: Box<dyn CASDatabase>,
             gas_allowance_for_chunk: u64,
+            promise_out_tx: Option<mpsc::UnboundedSender<Promise>>,
         }
 
+        impl UnwindSafe for Executable {}
```
Comment (ark0f) [inline ethexe/processor/src/handling/run.rs]: While I was verifying unwind safety I realized we always resume panic, so I suggest using `catch_unwind(AssertUnwindSafe(|| { ... }))` and unwrapping it inside `ThreadPool::spawn` so we don't need to think about it

File: ethexe/processor/src/handling/thread_pool.rs (hunk 8 above)
Comment (liferooter) [reply ethexe/processor/src/handling/thread_pool.rs]: Resolved by https://github.com/gear-tech/gear/pull/5217/commits/9e749c6566f366d6e35611a6b053309c718c6200

File: ethexe/processor/src/handling/run.rs (hunk 9 above)
Comment (liferooter) [reply ethexe/processor/src/handling/run.rs]: The problem is that panic is catched and resumed at different levels of our abstraction. Panics are handled in thread pool logic and resumed in our usage of it.

We can move panic resuming into thread pool logic, but will make the thead pool logic arguably harder to write test for and less obvious. Also while panic can always be resumed, it's hard to catch it back in async code. So I think the current behaviour is cleaner and more consistent.

But it's still true that the panic safety of `Executable` is derived from its usage, not from the type's nature, so I've replaced `impl UnwindSafe` with usage of `AssertUnwindSafe` in https://github.com/gear-tech/gear/pull/5217/commits/a73b0993225baecf6bd41160049f2f842ab473d4.

Comment (liferooter) [reply ethexe/processor/src/handling/run.rs]: Resolved by https://github.com/gear-tech/gear/pull/5217/commits/72d8534923ec52430b1b83bde8568cb3823b3d53
