### PR TITLE
fix(core): Allow waking the same message between waits

### LINKED ISSUE #2763: Allow waking the same message between waits
### Problem

Case of waking the same message in different executions should be allowed.

### Steps

See pallet-gear test referencing the issue

### Possible Solution

- Remove `awaken` field from `gear_core::message::context::ContextStore`
- Write migrations for `StoredDispatch` in `MessageQueue`, `DispatchStash` and `Waitlist` storages of `pallet-gear-messenger`
- Remove `#[should_panic]` attribute from test
// extra due to required migrations
- Remove `reply_sent` field from `gear_core::message::context::ContextStore` (Calling waits after replies is forbidden since auto-replies, so the field useless)

### Notes

_No response_

### Relevant Log Output

_No response_

### PR DESCRIPTION
**Pull request by mqxf**
Resolves #2763 

@reviewer-or-team

### CODE REVIEW

**Review by SabaunT — COMMENTED** [review]
Up to now seems ok. Need to implement migrations.

File: core/src/message/context.rs [hunk 1]
```diff
@@ -484,13 +483,9 @@ impl MessageContext {
 
     /// Wake message by it's message id.
     pub fn wake(&mut self, waker_id: MessageId, delay: u32) -> Result<(), Error> {
-        if self.store.awaken.insert(waker_id) {
-            self.outcome.awakening.push((waker_id, delay));
+        self.outcome.awakening.push((waker_id, delay));
```
Comment (breathx) [inline core/src/message/context.rs:486]: duplicate waking should still exist, discussed in dm

File: core/src/message/context.rs [hunk 2]
```diff
@@ -182,7 +182,6 @@ pub struct ContextStore {
     outgoing: BTreeMap<u32, Option<Payload>>,
     reply: Option<Payload>,
     initialized: BTreeSet<ProgramId>,
-    awaken: BTreeSet<MessageId>,
```
Comment (breathx) [inline core/src/message/context.rs:185]: not the context store points to storing in db

**Review by breathx — CHANGES_REQUESTED** [review]

**Review by breathx — CHANGES_REQUESTED** [review]
1) You don't need to store awakening at all
2) You need runtime migrations

**Comment by NikVolf** [comment]
Rebase this properly to master to remove all the commits above

File: pallets/gear-messenger/src/migrations.rs [hunk 3]
```diff
@@ -0,0 +1,327 @@
...
+use sp_std::marker::PhantomData;
+#[cfg(feature = "try-runtime")]
+use {
+    frame_support::codec::{Decode, Encode},
+    sp_std::vec::Vec,
+};
+
+pub struct MigrateToV3<T: Config>(PhantomData<T>);
+
+impl<T: Config> MigrateToV3<T> {
```
Comment (breathx) [inline pallets/gear-messenger/src/migrations.rs:38]: It's not necessary to be impl of MigrateToV3. Btw just Into within the module seems ok

File: pallets/gear-messenger/src/migrations.rs [hunk 4]
```diff
@@ -0,0 +1,327 @@
...
+                    next: store.next,
+                    value: StoredDispatch {
+                        kind: store.value.kind,
+                        message: store.value.message,
+                        context: store.value.context.map(Self::migrate_context_store),
+                    },
+                })
+            });
+
+            DispatchStash::<T>::translate(
```
Comment (breathx) [inline pallets/gear-messenger/src/migrations.rs:89]: btw you don't need to actually migrate dispatch stash because context there is always None. In this migrations you can change its data structure into sth like StoredDelayedDispatch { kind, msg }
In that case assert in tests that they're always empty and propagate here log::error in decode err case

File: pallets/gear-messenger/src/migrations.rs [hunk 5]
```diff
@@ -0,0 +1,327 @@
...
+                    reply: None,
+                    initialized: Default::default(),
+                    awaken: Default::default(),
+                    reply_sent: false,
+                    reservation_nonce: Default::default(),
+                    system_reservation: None,
+                }),
+            };
+
+            v2::Waitlist::<Test>::insert(
```
Comment (breathx) [inline pallets/gear-messenger/src/migrations.rs:289]: generate different dispatches pls in cycle

**Review by breathx — CHANGES_REQUESTED** [review]

File: core-processor/src/common.rs [hunk 6]
```diff
@@ -138,6 +140,7 @@ impl DispatchResult {
             system_reservation_context,
             page_update: Default::default(),
             allocations: Default::default(),
+            reply_sent: false,
```
[the remark this answers is not in the document]
Comment (mqxf) [reply core-processor/src/common.rs:143]: We need it in one place after program execution is over. It has to be saved since this is the only struct which is passed onto the processing.rs

[the remark this answers is not in the document]
Comment (mqxf) [reply core-processor/src/common.rs:143]: The value is also always reset to false, after every execution. Just the way we talked about. I cant just not initialize it or remove it from the struct or that would break the processing.rs

[the remark this answers is not in the document]
Comment (breathx) [reply core-processor/src/common.rs:143]: It's not always reset to false. But this fn is used only for case of non-executing with success. Specify it in a comment or add `reply_sent: bool` argument to the fn

[the remark this answers is not in the document]
Comment (mqxf) [reply core-processor/src/common.rs:143]: This function is only used to create a dispatchresult when there is no code execution whatsoever, ie, the export we wanted to call was not found (so we send a message but handle method doesnt exist), therefore a reply can never be sent. I can add a comment if you feel that is necessary, but due to this usecase being the way it is, i dont think it is necessary.

[the remark this answers is not in the document]
Comment (breathx) [reply core-processor/src/common.rs:143]: Nobody will remember this small thing if any new use-case of the fn will appear some time soon, so small comment is a must-have

File: pallets/gear-messenger/src/migrations.rs [hunk 7]
```diff
@@ -0,0 +1,347 @@
...
+    message::{ContextStore, StoredDispatch},
+};
+use sp_std::marker::PhantomData;
+#[cfg(feature = "try-runtime")]
+use {
+    frame_support::codec::{Decode, Encode},
+    sp_std::vec::Vec,
+};
+
+pub struct MigrateToV3<T: Config>(PhantomData<T>);
```
Comment (breathx) [inline pallets/gear-messenger/src/migrations.rs:36]: It's required to add this migrations to runtime otherwise it won't be executed! See runtime/vara/src/migrations.rs and add this to tuple.

**Review by breathx — CHANGES_REQUESTED** [review]
Never resolve conversations if they're not solved in any manner
@SabaunT please review

**Comment by mqxf** [comment]
Any conversations I resolve without comment means I believe that I have resolved them in the commit I pushed.

**Comment by breathx** [comment]
Still waiting of @SabaunT

**Comment by breathx** [comment]
@techraed please review

File: pallets/gear-messenger/src/migrations.rs [hunk 8]
```diff
@@ -0,0 +1,363 @@
...
+    };
+    use common::storage::{Interval, LinkedNode};
+    use frame_support::{pallet_prelude::StorageVersion, traits::OnRuntimeUpgrade};
+    use gear_core::{
+        ids::{MessageId, ProgramId},
+        message::{StoredDelayedDispatch, StoredMessage},
+    };
+
+    #[test]
+    fn migration_to_v3_works() {
```
Comment (techraed) [inline pallets/gear-messenger/src/migrations.rs:255]: can't see @breathx suggestions on tests to be implemented

**Review by techraed — CHANGES_REQUESTED** [review]
Everything seems fine except for `StoredDelayedDispatch`.
Waiting for additional review of @breathx

File: pallets/gear-messenger/src/migrations.rs (hunk 8 above)
Comment (mqxf) [reply pallets/gear-messenger/src/migrations.rs:255]: Except they are? Compared to the old code, it generates three different StorageDispatches, some with Some and some with None, adds them to the old storage, migrates to the new one, then asserts that they are migrated correctly. I'm decently sure that is what he meant when he first mentioned my tests which just ran the migrations without any assertions. Or am I missing something?

File: pallets/gear-messenger/src/migrations.rs [hunk 9]
```diff
@@ -0,0 +1,363 @@
...
+    }
+
+    pub struct DispatchesPrefix<T: Config>(PhantomData<T>);
+
+    impl<T: Config> StorageInstance for DispatchesPrefix<T> {
+        fn pallet_prefix() -> &'static str {
+            <<T as frame_system::Config>::PalletInfo as PalletInfo>::name::<Pallet<T>>()
+                .expect("No name found for the pallet in the runtime!")
+        }
+        const STORAGE_PREFIX: &'static str = "Dispatches";
```
[the remark this answers is not in the document]
Comment (mqxf) [reply pallets/gear-messenger/src/migrations.rs:183]: Pretty sure clippy would complain, since thats how the trait was defined, and it doesn't like it when I change the order of trait objects.

[the remark this answers is not in the document]
Comment (techraed) [reply pallets/gear-messenger/src/migrations.rs:183]: resolved then

File: core/src/message/stored.rs [hunk 10]
```diff
@@ -216,3 +216,59 @@ impl Deref for StoredDispatch {
...
+
+impl From<StoredDelayedDispatch> for StoredDispatch {
+    fn from(dispatch: StoredDelayedDispatch) -> Self {
+        StoredDispatch::new(dispatch.kind, dispatch.message, None)
+    }
+}
+
+/// Stored message with entry point.
+#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd, Decode, Encode, TypeInfo)]
+pub struct StoredDelayedDispatch {
```
[the remark this answers is not in the document]
Comment (techraed) [reply core/src/message/stored.rs:228]: Having a separate type for stored delayed dispatch is a good practice, but introducing it only for the migration seems odd.

Except for tests, we can check the `None` with `post_upgrade`, isn't it?
Instead of introducing a temporary type, I would recommend even make fields of `StoredDispatch` public until the migration is applied to the real chain and then revert this (also with migrations deletion).

@breathx what do you think?

File: pallets/gear-messenger/src/migrations.rs (hunk 8 above)
Comment (mqxf) [reply pallets/gear-messenger/src/migrations.rs:255]: hmm ok, I will do that

File: core/src/message/stored.rs (hunk 10 above)
[the remark this answers is not in the document]
Comment (breathx) [reply core/src/message/stored.rs:228]: @techraed,

The `StoredDelayedDispatch` is not temporary solution and even more is not for this migrations.

Dispatches that are just sent with delay are never have `ContextStore`. It's much better to see type-level guarantees for storing data instead of just every time check that it's none.

Implementing it within the PR is preferable way because we can fit two different independent (!) changes on storage in one migration cycle.

Speaking of migrations itself: we will perform transformation with checks: if some of the message context is not None, which is impossible in case of our runtime has no significant bugs, we will log::error it

File: core/src/message/stored.rs [hunk 11]
```diff
@@ -216,3 +216,59 @@ impl Deref for StoredDispatch {
...
+impl StoredDelayedDispatch {
+    /// Create new StoredDelayedDispatch.
+    pub fn new(kind: DispatchKind, message: StoredMessage) -> Self {
+        Self { kind, message }
+    }
+
+    /// Convert StoredDispatch into IncomingDispatch for program processing.
+    pub fn into_incoming(self, gas_limit: GasLimit) -> IncomingDispatch {
+        IncomingDispatch::new(self.kind, self.message.into_incoming(gas_limit), None)
+    }
```
Comment (breathx) [inline core/src/message/stored.rs:250]:
```suggestion
```

File: pallets/gear-messenger/src/migrations.rs [hunk 12]
```diff
@@ -0,0 +1,435 @@
...
+                weight = weight.saturating_add(T::DbWeight::get().reads_writes(1, 1));
+                Some(LinkedNode {
+                    next: store.next,
+                    value: store.value.into(),
+                })
+            });
+
+            DispatchStash::<T>::translate(
+                |_, store: (v2::StoredDispatch, Interval<BlockNumberFor<T>>)| {
+                    if store.0.context.is_some() {
```
Comment (breathx) [inline pallets/gear-messenger/src/migrations.rs:67]: could you add similar check in pre_uprade, that none of delayed dispatches has context?

File: pallets/gear-messenger/src/migrations.rs [hunk 13]
```diff
@@ -0,0 +1,435 @@
...
+                        log::error!("Previous context on StoredDispatch in DispatchStash should always be None, but was {:?}", store.0.context);
```
Comment (breathx) [inline pallets/gear-messenger/src/migrations.rs:68]: print message id instead of context

**Review by breathx — CHANGES_REQUESTED** [review]
Minor comments below. Otherwise lgtm.

@techraed

**Comment by breathx** [comment]
Kindly asking @ark0f to take a look as well

File: core/src/message/stored.rs (hunk 10 above)
[the remark this answers is not in the document]
Comment (techraed) [reply core/src/message/stored.rs:228]: > @techraed,
> 
> The `StoredDelayedDispatch` is not temporary solution and even more is not for this migrations.
> 
> Dispatches that are just sent with delay are never have `ContextStore`. It's much better to see type-level guarantees for storing data instead of just every time check that it's none.
> 
> Implementing it within the PR is preferable way because we can fit two different independent (!) changes on storage in one migration cycle.
> 
> Speaking of migrations itself: we will perform transformation with checks: if some of the message context is not None, which is impossible in case of our runtime has no significant bugs, we will log::error it

discussed, thank you.

**Review by techraed — APPROVED** [review]

File: pallets/gear-messenger/src/migrations.rs [hunk 14]
```diff
@@ -0,0 +1,435 @@
...
+        );
+
+        // 1 read for on chain storage version
+        let mut weight = T::DbWeight::get().reads(1);
+
+        if current == 3 && onchain == 2 {
+            Waitlist::<T>::translate(
+                |_, _, store: (v2::StoredDispatch, Interval<BlockNumberFor<T>>)| {
+                    weight = weight.saturating_add(T::DbWeight::get().reads_writes(1, 1));
+                    Some((store.0.into(), store.1))
```
Comment (ark0f) [inline pallets/gear-messenger/src/migrations.rs:53]:
```suggestion
                |_, _, (dispatch, interval): (v2::StoredDispatch, Interval<BlockNumberFor<T>>)| {
                    weight = weight.saturating_add(T::DbWeight::get().reads_writes(1, 1));
                    Some((dispatch.into(), interval))
```

File: core/src/message/stored.rs (hunk 10 above)
[the remark this answers is not in the document]
Comment (ark0f) [reply core/src/message/stored.rs:228]: This definitely should be described in comments

File: pallets/gear-messenger/src/lib.rs [hunk 15]
```diff
@@ -591,6 +593,7 @@ pub mod pallet {
         type MailboxSecondKey = MessageId;
         type MailboxedMessage = UserStoredMessage;
         type QueuedDispatch = StoredDispatch;
```
Comment (ark0f) [inline pallets/gear-messenger/src/lib.rs:595]: It looks like we need to migrate queue, too

File: pallets/gear-messenger/src/migrations.rs [hunk 16]
```diff
@@ -0,0 +1,435 @@
...
+        ProgramId,
+        Identity,
+        MessageId,
+        (StoredDispatch, Interval<BlockNumberFor<T>>),
+    >;
+}
+
+#[cfg(test)]
+#[cfg(feature = "try-runtime")]
+mod test {
```
Comment (ark0f) [inline pallets/gear-messenger/src/migrations.rs:244]:
```suggestion
mod tests {
```

File: pallets/gear-messenger/src/migrations.rs [hunk 17]
```diff
@@ -0,0 +1,435 @@
...
+                    random_dispatch(true),
+                    Interval {
+                        start: random(),
+                        finish: random(),
+                    },
+                )
+            })
+            .collect::<Vec<_>>();
+
+            for dispatch in dispatch_stash.iter() {
```
Comment (ark0f) [inline pallets/gear-messenger/src/migrations.rs:398]:
```suggestion
            for (msg_id, dispatch, interval) in dispatch_stash.clone() {
```

File: pallets/gear-messenger/src/migrations.rs [hunk 18]
```diff
@@ -0,0 +1,435 @@
...
+                v2::DispatchStash::<Test>::insert(
+                    dispatch.0,
+                    (dispatch.1.clone(), dispatch.2.clone()),
+                );
+            }
+
+            let state = MigrateToV3::<Test>::pre_upgrade().unwrap();
+            let _ = MigrateToV3::<Test>::on_runtime_upgrade();
```
Comment (ark0f) [inline pallets/gear-messenger/src/migrations.rs:406]: Assert weight is not zero

**Review by ark0f — DISMISSED** [review]

File: core/src/message/context.rs [hunk 19]
```diff
@@ -484,9 +498,8 @@ impl MessageContext {
 
     /// Wake message by it's message id.
     pub fn wake(&mut self, waker_id: MessageId, delay: u32) -> Result<(), Error> {
-        if self.store.awaken.insert(waker_id) {
+        if !self.outcome.awakening.iter().any(|v| v.0 == waker_id) {
```
[the remark this answers is not in the document]
Comment (mqxf) [reply core/src/message/context.rs:501]: This is a Vec<(MessageId, u64)>, contains does not take a function, but a value to compare with Eq, but we do not care what the u64 is since only if the MessageId is the same, it is a duplicate, therefore, I cannot use contains.

File: pallets/gear-messenger/src/migrations.rs (hunk 18 above)
Comment (mqxf) [reply pallets/gear-messenger/src/migrations.rs:406]: I did, a while ago, but it fails, because, Test weights for everything is zero, so it always adds zero for every read and write.

Comment (ark0f) [reply pallets/gear-messenger/src/migrations.rs:410]: https://github.com/gear-tech/gear/blob/ed3290bd7440103deb39dbfc715c3bc6794e90be/pallets/gear-messenger/src/mock.rs#L50

Replace to`DbWeight = RocksDbWeight`

File: pallets/gear-messenger/src/lib.rs (hunk 15 above)
Comment (breathx) [reply pallets/gear-messenger/src/lib.rs:595]: Migrations contain translation step for message queue (storage `Dispatches`)

Comment (mqxf) [reply pallets/gear-messenger/src/lib.rs:595]: We are migrating the inner storage of the queue, which is the StoredDispatch if i remember correctly

File: pallets/gear-messenger/src/migrations.rs [hunk 20]
```diff
@@ -87,7 +87,13 @@ impl<T: Config> OnRuntimeUpgrade for MigrateToV3<T> {
     fn pre_upgrade() -> Result<Vec<u8>, DispatchError> {
         let mut count = v2::Waitlist::<T>::iter().count();
         count += v2::Dispatches::<T>::iter().count();
-        count += v2::DispatchStash::<T>::iter().count();
+        count += v2::DispatchStash::<T>::iter().inspect(
+            |store| {
+                if store.1.0.context.is_some() {
+                    log::error!("Previous context on StoredDispatch in DispatchStash should always be None, but was Some for message id {:?}", store.1.0.message.id());
```
Comment (breathx) [inline pallets/gear-messenger/src/migrations.rs:93]: panic in pre-upgrade, it's only for testing purpose

**Review by breathx — APPROVED** [review]
