### PR TITLE
fix(core-backend): continue to adopt `LimitedStr`

### LINKED ISSUE #2098: use `TrimmedString` for global names in `GlobalsCtx`
### File Location(s)

[core-backend/common/src/lazy_pages.rs](https://github.com/gear-tech/gear/pull/1988/files/55e7748b7428483d5594328b4ad0295e2b312d5f#diff-37fb51e19dec925a94d0609cc0723eabd2b3d8d7759aaad92e883ec2b786e63a)

### Proposal

__IMPORTANT__: need to implement `TryFrom` for `TrimmedString`, using `From` is RESTRICTED!!!!

### PR DESCRIPTION
**Pull request by tltsutltsu**
Resolves #2098

The `LimitedStr<'a>` type is now used to replace `TrimmedString` and to access global variables. It provides the following API:
```rust
/// This method returns `Result<LimitedStr, &'static str>` and checks the maximum length of the input string
LimitedStr::try_from("&'a str");

/// This method returns `LimitedStr` and trims the string to the last char
LimitedStr::from(String::new());

/// This method is used to create `LimitedStr` from `&str`
LimitedStr::from_small_str("global name");
```

@gear-tech/dev

### CODE REVIEW

File: runtime-interface/src/lib.rs [hunk 1]
```diff
@@ -72,8 +73,7 @@ impl PassBy for LazyPagesProgramContext {
 #[codec(crate = codec)]
 pub struct LazyPagesRuntimeContext {
     pub page_sizes: Vec<u32>,
-    // TODO: considering change global name types to `TrimmedString` (issue #2098)
```
Comment (breathx) [inline runtime-interface/src/lib.rs:75]: Need to figure out does this changes invalidates runtime interfaces
(check that LimitedStr encodes like String)

**Review by breathx — CHANGES_REQUESTED** [review]
Seems ok, the only I care about is compatibility

**Comment by breathx** [comment]
You can ask @grishasobol for help in such research

File: core-backend/common/src/utils.rs [hunk 2]
```diff
@@ -87,25 +58,55 @@ fn smart_truncate(s: &mut String, max_bytes: usize) {
...
-    const INIT_ERROR_MSG: &'static str = concat!(
+    const INIT_ERROR_MSG: &str = concat!(
         "String must be less than ",
         stringify!(TRIMMED_MAX_LEN),
         " bytes."
     );
 
-    pub fn new(s: &'a str) -> Result<Self, &'static str> {
+    #[track_caller]
+    pub const fn from_small_str(s: &'a str) -> Self {
```
Comment (grishasobol) [inline core-backend/common/src/utils.rs:81]: If we really wanna use panic here, then use unwrap_or_else, as it is common way. Also, why do we need to specify str lifetime ?

Actually I'm not in glad with using panic here. Better to return an error, and make unwrap_or_else in places where we really wanna panic in wrong case. And you have already try_from

**Review by grishasobol — CHANGES_REQUESTED** [review]

File: core-backend/common/src/utils.rs (hunk 2 above)
Comment (StackOverflowExcept1on) [reply core-backend/common/src/utils.rs:81]: We cannot use `try_from().expect("msg")` in constant context. The main point of `LimitedStr::from_small_str` is optimization for global names.
```rust
/// zero cost
const GLOBAL_NAMES: &[LimitedStr<'static>] = &[
    LimitedStr::from_small_str(GLOBAL_NAME_GAS),
];

/// `try_from` isn't const fn, `except(...)` isn't stabilized yet in const fns
const GLOBAL: LimitedStr<'static> = LimitedStr::try_from(GLOBAL_NAME_GAS).except("failed")
```

Comment (grishasobol) [reply core-backend/common/src/utils.rs:81]: Ok agree

**Review by grishasobol — COMMENTED** [review]
I wanna to investigate this case more deeply, so will not remove `request changes` currently. Please wait 1-2 days

File: core-backend/common/src/utils.rs [hunk 3]
```diff
@@ -87,25 +58,55 @@ fn smart_truncate(s: &mut String, max_bytes: usize) {
...
+/// Wrapped string to fit `core-backend::TRIMMED_MAX_LEN` amount of bytes.
+///
+/// The `Cow` is used to avoid allocating a new `String` when the `LimitedStr` is
+/// created from a `&str`.
+///
+/// Plain `str` is not used because it can't be properly encoded/decoded via scale codec.
+#[derive(
+    TypeInfo, Encode, Decode, Debug, Clone, derive_more::Display, PartialEq, Eq, PartialOrd, Ord,
+)]
+#[codec(crate = scale)]
```
Comment (grishasobol) [inline core-backend/common/src/utils.rs:70]: Could you explain me: why do we need this #[codec(crate = scale)] ?

**Review by grishasobol — APPROVED** [review]

File: core-backend/common/src/utils.rs (hunk 3 above)
Comment (breathx) [reply core-backend/common/src/utils.rs:70]: > Could you explain me: why do we need this #[codec(crate = scale)] ?

It allows don't depend from parity_scale_codec, but at the same time use their derive macros from `pub extern crate codec` of other libs.
That caused by internal implementation of these derive macros.

File: core-backend/common/src/utils.rs [hunk 4]
```diff
@@ -87,25 +58,55 @@ fn smart_truncate(s: &mut String, max_bytes: usize) {
...
+        Self(Cow::Borrowed(s))
+    }
+
+    pub fn as_str(&self) -> &str {
+        self.0.as_ref()
+    }
+}
+
+impl<'a> TryFrom<&'a str> for LimitedStr<'a> {
+    type Error = &'static str;
```
Comment (ark0f) [inline core-backend/common/src/utils.rs:95]: I suggest
```suggestion
    type Error = LimitedStrTryFromError;
```

because `&'static str` is not convenient to match and work with in general

File: core-backend/common/src/utils.rs (hunk 3 above)
Comment (grishasobol) [reply core-backend/common/src/utils.rs:70]: But.. as I can see scale is parity scale codec:
https://github.com/paritytech/scale-info/blob/cc97f4c6496acf0f92d9caa45856331f094a7f38/Cargo.toml#L23

So, why we need to specify this, if it's by default

File: core-backend/common/src/utils.rs [hunk 5]
```diff
@@ -87,25 +58,58 @@ fn smart_truncate(s: &mut String, max_bytes: usize) {
     }
 }
 
-#[derive(Debug, Copy, Clone, derive_more::Display)]
-pub struct LimitedStr<'a>(&'a str);
+/// Wrapped string to fit `core-backend::TRIMMED_MAX_LEN` amount of bytes.
```
Comment (breathx) [inline core-backend/common/src/utils.rs:61]:
```suggestion
/// Wrapped string to fit `core_backend::TRIMMED_MAX_LEN` amount of bytes.
```

**Review by breathx — APPROVED** [review]
Fetch master please
