### PR TITLE
fix(scripts): rewrite `install.sh` in POSIX way 

### LINKED ISSUE #3336: `curl ... https://get.gear.rs/install.sh | sh` doesn't work on ubuntu 22.04
### Problem

```
$ curl --proto '=https' --tlsv1.2 -sSf https://get.gear.rs/install.sh | sh
sh: 3: set: Illegal option -o pipefail
```

### Steps

1. copy the command from readme
2. run it on ubuntu 22.04

### Possible Solution

_No response_

### Notes

_No response_

### Relevant Log Output

_No response_

### PR DESCRIPTION
**Pull request by StackOverflowExcept1on**
Resolves #3336

This PR fixes the `install.sh` script to work with `/bin/sh`. I also checked the script using [shellcheck](https://www.shellcheck.net) and in the ubuntu docker container.

### CODE REVIEW

File: scripts/install.sh [hunk 1]
```diff
@@ -1,13 +1,13 @@
...
+set -eu
 
-if [ ! -z ${GITHUB_ACTIONS-} ]; then
+if [ -n "${GITHUB_ACTIONS-}" ]; then
   set -x
 fi
 
 help() {
-  cat <<'EOF'
+  cat <<EOF
```
Comment (breathx) [inline scripts/install.sh:10]:
```suggestion
  cat << EOF
```

**Review by breathx — APPROVED** [review]

**Review by ukint-vs — APPROVED** [review]
